function cfg = configureOdsZaRadius(cfg,zaRadiusKm)
%configureOdsZaRadius Apply one consistent geographic ZA radius.
%   CFG = configureOdsZaRadius(CFG,ZARADIUSKM) updates every model
%   field that depends on the no-user/active-beam-center radius. Use this
%   function instead of changing individual cfg.za fields separately.

arguments
    cfg (1,1) struct
    zaRadiusKm (1,1) double {mustBeFinite,mustBeNonnegative}
end

requiredGroups = ["meta","site","receiver","za","ods", ...
    "calibration","rf","output"];
for groupName = requiredGroups
    assert(isfield(cfg,groupName),"ODS:ZaMissingConfigGroup", ...
        "Cannot configure ZA because cfg.%s is missing.",groupName);
end
assert(zaRadiusKm < cfg.ods.outerMinimumBeamCenterDistanceKm, ...
    "ODS:ZaRetaskRange", ...
    "ZA radius must be less than the %.6g km outer-retask distance.", ...
    cfg.ods.outerMinimumBeamCenterDistanceKm);

zaLabel = string(sprintf("%.6g",zaRadiusKm));
zaToken = replace(zaLabel,".","p");

cfg.za.enabled = true;
cfg.za.protectedCoreRadiusKm = zaRadiusKm;
cfg.za.minimumActiveBeamCenterDistanceKm = zaRadiusKm;
cfg.za.definition = compose( ...
    "No offered D2D user demand/active beam center inside %s km of the protected receiver", ...
    zaLabel);
cfg.za.sourceStatus = compose( ...
    "User-configured %s-km geographic demand-exclusion radius; blocked demand is not reassigned.", ...
    zaLabel);

cfg.calibration.sourceStatus = compose( ...
    "Provisional cross-service engineering calibration fixed at absolute " + ...
    "%.6g-%.6g km distances and independent of the %.6g-km ZA; receiver- " + ...
    "and band-specific measurements supersede it.", ...
    cfg.calibration.rampStartDistanceKm, ...
    cfg.calibration.fullCorrectionDistanceKm,zaRadiusKm);

cfg.meta.baselineId = string(cfg.receiver.serviceCode) + ...
    "-30-SPOT-60-FOR-" + ...
    upper(replace(string(sprintf("%.6g", ...
    cfg.rf.maximumBeamEirpDensityDbwPerMHz)),".","p")) + ...
    "DBW-MHZ-GT15P2-INDEPENDENT-DEMAND-ZA" + upper(zaToken);
end
