function heightInfo = resolveSiteHeights(latitudeDeg,longitudeDeg, ...
    antennaHeightAglM,options)
%resolveSiteHeights Resolve DEM, orthometric, geoid, and ellipsoid heights.
%   The default DEM source is the USGS 3DEP Elevation Point Query Service.
%   GroundOrthometricHeightM is an advanced deterministic override intended
%   for offline reruns with a previously saved DEM result.

arguments
    latitudeDeg (1,1) double
    longitudeDeg (1,1) double
    antennaHeightAglM (1,1) double {mustBePositive}
    options.GroundOrthometricHeightM (1,1) double = NaN
    options.DemEndpoint (1,1) string = ...
        "https://epqs.nationalmap.gov/v1/json"
    options.TimeoutSeconds (1,1) double {mustBePositive} = 30
    options.GeoidModel (1,1) string = "EGM96"
end

assert(isfinite(latitudeDeg) && latitudeDeg >= -90 && latitudeDeg <= 90, ...
    "ODS:Latitude","Latitude must lie within [-90, 90] degrees.");
assert(isfinite(longitudeDeg) && longitudeDeg >= -180 && ...
    longitudeDeg <= 180,"ODS:Longitude", ...
    "Longitude must lie within [-180, 180] degrees.");

if isfinite(options.GroundOrthometricHeightM)
    groundOrthometricHeightM = options.GroundOrthometricHeightM;
    demSource = "User-supplied cached DEM elevation";
    demResolutionM = NaN;
    demRasterId = "not-reported";
    rawDemResponse = struct( ...
        "value",groundOrthometricHeightM, ...
        "source","GroundOrthometricHeightM option");
else
    queryUrl = compose( ...
        "%s?x=%.10f&y=%.10f&wkid=4326&units=Meters&includeDate=False", ...
        strip(options.DemEndpoint,"right","/"),longitudeDeg,latitudeDeg);
    try
        rawDemResponse = webread(queryUrl,weboptions( ...
            Timeout=options.TimeoutSeconds,ContentType="json"));
    catch exception
        error("ODS:DemLookup", ...
            "USGS 3DEP DEM lookup failed for %.8f, %.8f. " + ...
            "Retry with network access or supply the saved DEM value through " + ...
            "DemGroundElevationM. Original error: %s", ...
            latitudeDeg,longitudeDeg,exception.message);
    end
    assert(isstruct(rawDemResponse) && isfield(rawDemResponse,"value"), ...
        "ODS:DemResponse","The DEM service response did not contain a value field.");
    groundOrthometricHeightM = str2double(string(rawDemResponse.value));
    assert(isfinite(groundOrthometricHeightM) && ...
        groundOrthometricHeightM > -1000 && groundOrthometricHeightM < 10000, ...
        "ODS:DemElevation","The DEM service returned an invalid elevation value.");
    demSource = "USGS 3DEP Elevation Point Query Service";
    demResolutionM = getNumericField(rawDemResponse,"resolution",NaN);
    demRasterId = getStringField(rawDemResponse,"rasterId","not-reported");
end

geoidModel = upper(strip(options.GeoidModel));
assert(any(geoidModel == ["EGM96","EGM2008"]),"ODS:GeoidModel", ...
    "GeoidModel must be EGM96 or EGM2008.");
% geoidheight expects longitude in [0, 360]. Its output N follows h=H+N.
wrappedLongitudeDeg = mod(longitudeDeg,360);
try
    geoidUndulationM = geoidheight(latitudeDeg,wrappedLongitudeDeg, ...
        char(geoidModel));
catch exception
    error("ODS:GeoidLookup", ...
        "Unable to calculate %s geoid undulation. Original error: %s", ...
        geoidModel,exception.message);
end

antennaOrthometricHeightM = groundOrthometricHeightM + antennaHeightAglM;
antennaEllipsoidalHeightM = antennaOrthometricHeightM + geoidUndulationM;
heightInfo = struct( ...
    "latitudeDeg",latitudeDeg, ...
    "longitudeDeg",longitudeDeg, ...
    "antennaHeightAglM",antennaHeightAglM, ...
    "groundOrthometricHeightM",groundOrthometricHeightM, ...
    "antennaOrthometricHeightM",antennaOrthometricHeightM, ...
    "geoidUndulationM",geoidUndulationM, ...
    "antennaEllipsoidalHeightM",antennaEllipsoidalHeightM, ...
    "demSource",demSource, ...
    "demEndpoint",options.DemEndpoint, ...
    "demResolutionM",demResolutionM, ...
    "demRasterId",demRasterId, ...
    "geoidModel",geoidModel, ...
    "heightEquation","h_ellipsoid = H_DEM + h_AGL + N_geoid", ...
    "rawDemResponse",rawDemResponse);
end

function value = getNumericField(source,fieldName,defaultValue)
if isfield(source,fieldName)
    value = str2double(string(source.(fieldName)));
    if ~isfinite(value)
        value = defaultValue;
    end
else
    value = defaultValue;
end
end

function value = getStringField(source,fieldName,defaultValue)
if isfield(source,fieldName)
    value = string(source.(fieldName));
else
    value = string(defaultValue);
end
end
