function results = runOdsAngleSimulator(options)
%runOdsAngleSimulator - Calculate ODS angles for one DCS or GRB site
%   RESULTS = runOdsAngleSimulator() interactively asks for the protected
%   site's latitude and longitude, antenna diameter, antenna feed height
%   above local ground, DCS or GRB service, selected GOES satellite, and
%   geographic zone-of-avoidance (ZA) radius. It then runs a deterministic,
%   phase-diverse multi-window simulation and writes a complete run record.
%
%   Angles are measured from the protected antenna's selected GOES
%   boresight. They are not elevation angles and are not measured from
%   zenith.
%
%   Programmatic example using a cached DEM height:
%     results = runOdsAngleSimulator( ...
%         LatitudeDeg=37.94651, LongitudeDeg=-75.46210, ...
%         AntennaDiameterM=16.4, AntennaHeightAglM=5, ...
%         Service="DCS", GoesSatellite="GOES East", ...
%         ZaRadiusKm=30, DemGroundElevationM=9.465678215, ...
%         ItuDigitalMapsFolder="C:\data\itu_maps");
%
%   The public baseline fixes 43 dBW/MHz maximum EIRP density per active
%   spot and protects I/N <= -6 dB at 95% modeled availability. Advanced
%   name-value arguments expose those and the ensemble controls for
%   sensitivity studies. See README.md before interpreting a result.
%
%   See also checkOdsInstallation, runOdsEnsemble.

arguments
    options.LatitudeDeg (1,1) double = NaN
    options.LongitudeDeg (1,1) double = NaN
    options.AntennaDiameterM (1,1) double = NaN
    options.AntennaHeightAglM (1,1) double = NaN
    options.Service (1,1) string = ""
    options.GoesSatellite (1,1) string = ""
    options.ZaRadiusKm (1,1) double = NaN
    options.SiteName (1,1) string = ""
    options.OutputRoot (1,1) string = fullfile( ...
        fileparts(mfilename("fullpath")),"runs")
    options.RunLabel (1,1) string = ""
    options.ProtectionCriterionDb (1,1) double = -6
    options.PrimaryAvailabilityPercent (1,1) double = 95
    options.BeamEirpDensityDbwPerMHz (1,1) double ...
        {mustBeFinite,mustBePositive} = 43
    options.DemGroundElevationM (1,1) double = NaN
    options.DemEndpoint (1,1) string = ...
        "https://epqs.nationalmap.gov/v1/json"
    options.DemTimeoutSeconds (1,1) double {mustBePositive} = 30
    options.GeoidModel (1,1) string = "EGM96"
    options.ItuDigitalMapsFolder (1,1) string = ""
    options.AtmosphericLookupFile (1,1) string = ""
    options.InitialWindowCount (1,1) double ...
        {mustBeInteger,mustBePositive} = 12
    options.MinimumWindowCount (1,1) double ...
        {mustBeInteger,mustBePositive} = 24
    options.MaximumWindowCount (1,1) double ...
        {mustBeInteger,mustBePositive} = 48
    options.WindowBatchSize (1,1) double ...
        {mustBeInteger,mustBePositive} = 4
    options.ConvergenceToleranceDeg (1,1) double ...
        {mustBeFinite,mustBePositive} = 1
    options.RequiredStableBatches (1,1) double ...
        {mustBeInteger,mustBePositive} = 2
    options.FineHalfWidthDeg (1,1) double ...
        {mustBeFinite,mustBePositive} = 10
    options.ReferenceEpoch (1,1) datetime = datetime( ...
        2026,8,1,0,0,0,TimeZone="UTC")
    options.TimeStepSec (1,1) double ...
        {mustBeFinite,mustBePositive} = 2
    options.WindowDurationSec (1,1) double ...
        {mustBeFinite,mustBePositive} = 7200
    options.WarmupSec (1,1) double ...
        {mustBeFinite,mustBeNonnegative} = 120
    options.FutureGuardSec (1,1) double ...
        {mustBeFinite,mustBeNonnegative} = 16
    options.MonteCarloRuns (1,1) double ...
        {mustBeInteger,mustBePositive} = 4
    options.BaseGeometrySeed (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 16751695
    options.BaseTrafficSeed (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 91675169
    options.SaveCheckpoints (1,1) logical = false
    options.DryRun (1,1) logical = false
end

projectFolder = string(fileparts(mfilename("fullpath")));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(projectFolder,fullfile(projectFolder,"config"), ...
    fullfile(projectFolder,"src"));

fprintf("\nGOES DCS/GRB ODS Angle Simulator\n");
fprintf("Angles are measured from the selected GOES boresight.\n\n");
latitudeDeg = askNumber(options.LatitudeDeg, ...
    "1a - Protected-site latitude (deg, north positive): ");
longitudeDeg = askNumber(options.LongitudeDeg, ...
    "1b - Protected-site longitude (deg, east positive): ");
diameterM = askNumber(options.AntennaDiameterM, ...
    "2  - Protected antenna diameter (m): ");
antennaHeightAglM = askNumber(options.AntennaHeightAglM, ...
    "3  - Antenna feed/phase-center height above local ground (m): ");
service = askService(options.Service);
goesSatellite = askGoesSatellite(options.GoesSatellite);
zaRadiusKm = askNumber(options.ZaRadiusKm, ...
    "6  - Geographic demand-exclusion ZA radius (km): ");

validateUserInputs(latitudeDeg,longitudeDeg,diameterM, ...
    antennaHeightAglM,zaRadiusKm,options);
validateEnsembleInputs(options);

if isnan(options.DemGroundElevationM)
    fprintf("The DEM lookup sends the entered coordinates to the USGS EPQS service.\n");
end
fprintf("Resolving DEM and geoid heights...\n");
heightInfo = resolveSiteHeights(latitudeDeg,longitudeDeg, ...
    antennaHeightAglM, ...
    GroundOrthometricHeightM=options.DemGroundElevationM, ...
    DemEndpoint=options.DemEndpoint, ...
    TimeoutSeconds=options.DemTimeoutSeconds, ...
    GeoidModel=options.GeoidModel);

[boresightLongitudeDeg,boresightSource] = goesLongitude(goesSatellite);
expectedBoresightElevationDeg = calculateGoesElevation( ...
    latitudeDeg,longitudeDeg,heightInfo.antennaEllipsoidalHeightM, ...
    boresightLongitudeDeg);
assert(expectedBoresightElevationDeg > 0,"ODS:GoesBelowHorizon", ...
    "The selected %s slot is below the geometric horizon at this site " + ...
    "(boresight elevation %.3f deg). Select a visible GOES satellite.", ...
    goesSatellite,expectedBoresightElevationDeg);

caseId = buildCaseId(latitudeDeg,longitudeDeg,diameterM,service, ...
    goesSatellite,zaRadiusKm,antennaHeightAglM,options.RunLabel);
outputFolder = createUniqueOutputFolder(options.OutputRoot,caseId);
writeHeightProvenance(heightInfo,outputFolder);

siteName = strip(options.SiteName);
if strlength(siteName) == 0
    siteName = "User-defined protected site";
end
request = struct( ...
    "SiteName",siteName,"SiteId",caseId, ...
    "LatitudeDeg",latitudeDeg,"LongitudeDeg",longitudeDeg, ...
    "AntennaDiameterM",diameterM,"Service",service, ...
    "GoesSatellite",goesSatellite, ...
    "BoresightLongitudeDeg",boresightLongitudeDeg, ...
    "ExpectedBoresightElevationDeg",expectedBoresightElevationDeg, ...
    "BoresightLongitudeSource",boresightSource, ...
    "ZaRadiusKm",zaRadiusKm,"AntennaHeightAglM",antennaHeightAglM, ...
    "GroundOrthometricHeightM",heightInfo.groundOrthometricHeightM, ...
    "AntennaOrthometricHeightM",heightInfo.antennaOrthometricHeightM, ...
    "GeoidUndulationM",heightInfo.geoidUndulationM, ...
    "AntennaEllipsoidalHeightM",heightInfo.antennaEllipsoidalHeightM, ...
    "DemSource",heightInfo.demSource, ...
    "DemResolutionM",heightInfo.demResolutionM, ...
    "DemRasterId",heightInfo.demRasterId, ...
    "GeoidModel",heightInfo.geoidModel, ...
    "ProtectionCriterionDb",options.ProtectionCriterionDb, ...
    "PrimaryAvailabilityPercent",options.PrimaryAvailabilityPercent, ...
    "BeamEirpDensityDbwPerMHz",options.BeamEirpDensityDbwPerMHz, ...
    "OutputFolder",outputFolder);
cfg = defaultOdsConfig(request,projectFolder);
writeInputTable(request,cfg,outputFolder);
displayConfiguration(cfg,options);
save(fullfile(outputFolder,"input_configuration.mat"),"request","cfg","options");

if options.DryRun
    results = struct("config",cfg,"request",request, ...
        "status","DRY RUN - SIMULATION NOT EXECUTED", ...
        "outputFolder",outputFolder);
    fprintf("\nDry run complete; no ODS angles were calculated.\n");
    fprintf("Output folder: %s\n",outputFolder);
    clear pathCleanup
    return
end

if strlength(strip(options.AtmosphericLookupFile)) > 0
    assert(isfile(options.AtmosphericLookupFile), ...
        "ODS:AtmosphericLookupFile", ...
        "AtmosphericLookupFile does not exist: %s", ...
        options.AtmosphericLookupFile);
    copyfile(options.AtmosphericLookupFile, ...
        cfg.propagation.atmosphericLookupFile);
else
    mapFolder = locateItuMaps(options.ItuDigitalMapsFolder,projectFolder);
    fprintf("Generating the site/service-specific P.618 lookup...\n");
    generateP618AtmosphericLookup(cfg,mapFolder, ...
        cfg.propagation.atmosphericLookupFile);
end

results = runOdsEnsemble(cfg,OutputFolder=outputFolder, ...
    InitialWindowCount=options.InitialWindowCount, ...
    MinimumWindowCount=options.MinimumWindowCount, ...
    MaximumWindowCount=options.MaximumWindowCount, ...
    WindowBatchSize=options.WindowBatchSize, ...
    ConvergenceToleranceDeg=options.ConvergenceToleranceDeg, ...
    RequiredStableBatches=options.RequiredStableBatches, ...
    FineHalfWidthDeg=options.FineHalfWidthDeg, ...
    ReferenceEpoch=options.ReferenceEpoch, ...
    TimeStepSec=options.TimeStepSec, ...
    WindowDurationSec=options.WindowDurationSec, ...
    WarmupSec=options.WarmupSec, ...
    FutureGuardSec=options.FutureGuardSec, ...
    MonteCarloRuns=options.MonteCarloRuns, ...
    BaseGeometrySeed=options.BaseGeometrySeed, ...
    BaseTrafficSeed=options.BaseTrafficSeed, ...
    SaveCheckpoints=options.SaveCheckpoints);
results.config = cfg;
results.request = request;
fprintf("\nPublic run complete: %s\n",results.status);
fprintf("  Outer angle from boresight: %.2f deg\n", ...
    results.primary.outerAngleDeg);
fprintf("  Inner angle from boresight: %.2f deg\n", ...
    results.primary.innerAngleDeg);
fprintf("  Output folder: %s\n",results.outputFolder);
clear pathCleanup
end

function value = askNumber(currentValue,promptText)
value = currentValue;
if isnan(value)
    raw = input(promptText,"s");
    value = str2double(strip(string(raw)));
    assert(isscalar(value) && isfinite(value),"ODS:NumericInput", ...
        "Enter one finite numeric value.");
end
end

function service = askService(currentValue)
if strlength(strip(currentValue)) == 0
    raw = input("4  - Receiver service (1=DCS, 2=GRB): ","s");
else
    raw = currentValue;
end
token = lower(strip(string(raw)));
if any(token == ["1","dcs","data collection system"])
    service = "DCS";
elseif any(token == ["2","grb","goes rebroadcast"])
    service = "GRB";
else
    error("ODS:Service","Service must be DCS/1 or GRB/2.");
end
end

function satellite = askGoesSatellite(currentValue)
if strlength(strip(currentValue)) == 0
    raw = input("5  - GOES boresight (1=East, 2=West, 3=Backup): ","s");
else
    raw = currentValue;
end
token = lower(strip(string(raw)));
if any(token == ["1","east","goes east","goes-east"])
    satellite = "GOES East";
elseif any(token == ["2","west","goes west","goes-west"])
    satellite = "GOES West";
elseif any(token == ["3","backup","goes backup","goes-backup"])
    satellite = "GOES Backup";
else
    error("ODS:GoesSatellite", ...
        "GOES satellite must be East/1, West/2, or Backup/3.");
end
end

function validateUserInputs(lat,lon,diameter,heightAgl,za,options)
assert(isfinite(lat) && lat >= -90 && lat <= 90,"ODS:Latitude", ...
    "Latitude must lie within [-90, 90] degrees.");
assert(isfinite(lon) && lon >= -180 && lon <= 180,"ODS:Longitude", ...
    "Longitude must lie within [-180, 180] degrees.");
assert(isfinite(diameter) && diameter > 0,"ODS:AntennaDiameter", ...
    "Antenna diameter must be positive.");
assert(isfinite(heightAgl) && heightAgl > 0,"ODS:AntennaHeight", ...
    "Antenna feed/phase-center height above ground must be positive.");
assert(isfinite(za) && za >= 0 && za < 180,"ODS:ZaRadius", ...
    "ZA radius must lie in [0, 180) km for the current 180-km retask rule.");
assert(isfinite(options.ProtectionCriterionDb),"ODS:Criterion", ...
    "ProtectionCriterionDb must be finite.");
assert(isfinite(options.PrimaryAvailabilityPercent) && ...
    options.PrimaryAvailabilityPercent > 0 && ...
    options.PrimaryAvailabilityPercent <= 100,"ODS:Availability", ...
    "PrimaryAvailabilityPercent must lie within (0, 100].");
end

function validateEnsembleInputs(options)
assert(options.InitialWindowCount >= 12 && ...
    mod(options.InitialWindowCount,options.WindowBatchSize) == 0, ...
    "ODS:InitialEnsembleWindows", ...
    "InitialWindowCount must be at least 12 and divisible by WindowBatchSize.");
assert(options.MinimumWindowCount >= options.InitialWindowCount && ...
    mod(options.MinimumWindowCount,options.WindowBatchSize) == 0, ...
    "ODS:MinimumEnsembleWindows", ...
    "MinimumWindowCount must be at least InitialWindowCount and divisible by WindowBatchSize.");
assert(options.MaximumWindowCount >= options.MinimumWindowCount && ...
    mod(options.MaximumWindowCount,options.WindowBatchSize) == 0, ...
    "ODS:MaximumEnsembleWindows", ...
    "MaximumWindowCount must be at least MinimumWindowCount and divisible by WindowBatchSize.");
assert(mod(options.WindowDurationSec,options.TimeStepSec) == 0 && ...
    mod(options.WarmupSec,options.TimeStepSec) == 0 && ...
    mod(options.FutureGuardSec,options.TimeStepSec) == 0, ...
    "ODS:EnsembleGridAlignment", ...
    "Window duration and both guards must be integer multiples of TimeStepSec.");
requiredPredictionGuardSec = 16;
assert(options.FutureGuardSec >= requiredPredictionGuardSec, ...
    "ODS:PredictionGuard", ...
    "FutureGuardSec must be at least %.6g s for the 15-s command latency " + ...
    "plus 1-s clock allowance.",requiredPredictionGuardSec);
assert(~isnat(options.ReferenceEpoch) && ...
    strlength(string(options.ReferenceEpoch.TimeZone)) > 0, ...
    "ODS:ReferenceEpochTimeZone", ...
    "ReferenceEpoch must have an explicit time zone; UTC is recommended.");
end

function [longitudeDeg,source] = goesLongitude(satellite)
switch satellite
    case "GOES East"
        longitudeDeg = -75.2;
        source = "Configured ideal GOES-East slot at 75.2 W";
    case "GOES West"
        longitudeDeg = -137.0;
        source = "Configured ideal GOES-West slot at 137.0 W";
    otherwise
        longitudeDeg = -104.7;
        source = "Configured ideal GOES Backup slot at 104.7 W";
end
end

function elevationDeg = calculateGoesElevation(latDeg,lonDeg,heightM,geoLonDeg)
stationEcef = geodeticToEcefLocal(latDeg,lonDeg,heightM);
geoRadiusM = 42164137;
geoLonRad = deg2rad(geoLonDeg);
geoEcef = geoRadiusM*[cos(geoLonRad);sin(geoLonRad);0];
boresight = geoEcef-stationEcef;
boresight = boresight/norm(boresight);
up = [cosd(latDeg)*cosd(lonDeg); ...
    cosd(latDeg)*sind(lonDeg);sind(latDeg)];
elevationDeg = asind(max(-1,min(1,up.'*boresight)));
end

function ecef = geodeticToEcefLocal(latDeg,lonDeg,heightM)
semiMajorAxisM = 6378137;
flattening = 1/298.257223563;
eccentricitySquared = flattening*(2-flattening);
latRad = deg2rad(latDeg);
lonRad = deg2rad(lonDeg);
primeVerticalRadius = semiMajorAxisM / ...
    sqrt(1-eccentricitySquared*sin(latRad)^2);
ecef = [(primeVerticalRadius+heightM)*cos(latRad)*cos(lonRad); ...
    (primeVerticalRadius+heightM)*cos(latRad)*sin(lonRad); ...
    (primeVerticalRadius*(1-eccentricitySquared)+heightM)*sin(latRad)];
end

function caseId = buildCaseId(lat,lon,diameter,service,satellite,za, ...
    heightAgl,label)
parts = [lower(service),"lat" + numberToken(lat,5), ...
    "lon" + numberToken(lon,5),"d" + numberToken(diameter,2) + "m", ...
    lower(replace(satellite," ","_")), ...
    "za" + numberToken(za,1) + "km", ...
    "hagl" + numberToken(heightAgl,1) + "m"];
caseId = strjoin(parts,"_");
if strlength(strip(label)) > 0
    safeLabel = lower(regexprep(strip(label),"[^A-Za-z0-9]+","_"));
    safeLabel = regexprep(safeLabel,"^_+|_+$","");
    assert(strlength(safeLabel) > 0,"ODS:RunLabel", ...
        "RunLabel must contain at least one letter or digit.");
    caseId = caseId + "_" + safeLabel;
end
end

function token = numberToken(value,decimalPlaces)
format = "%." + string(decimalPlaces) + "f";
token = string(sprintf(format,value));
token = replace(token,"-","m");
token = replace(token,"+","p");
token = replace(token,".","p");
end

function outputFolder = createUniqueOutputFolder(outputRoot,caseId)
assert(strlength(strip(outputRoot)) > 0,"ODS:OutputRoot", ...
    "OutputRoot must not be empty.");
if ~isfolder(outputRoot), mkdir(outputRoot); end
stamp = string(datetime("now",TimeZone="UTC"), ...
    "yyyyMMdd'T'HHmmss_SSS'Z'");
outputFolder = fullfile(outputRoot,caseId + "_" + stamp);
suffix = 1;
while isfolder(outputFolder)
    outputFolder = fullfile(outputRoot,caseId + "_" + stamp + ...
        "_" + string(suffix));
    suffix = suffix + 1;
end
mkdir(outputFolder);
end

function mapFolder = locateItuMaps(requestedFolder,projectFolder)
candidates = strings(0,1);
if strlength(strip(requestedFolder)) > 0
    candidates(end+1) = requestedFolder;
end
environmentFolder = string(getenv("MATLAB_ITU_MAPS_FOLDER"));
if strlength(strip(environmentFolder)) > 0
    candidates(end+1) = environmentFolder;
end
candidates(end+1) = fullfile(projectFolder,"data","itu_maps");
requiredFiles = ["maps.mat","p836.mat","p837.mat","p840.mat"];
mapFolder = "";
for candidate = reshape(candidates,1,[])
    if isfolder(candidate) && all(isfile(fullfile(candidate,requiredFiles)))
        mapFolder = candidate;
        break
    end
end
assert(strlength(mapFolder) > 0,"ODS:MissingItuMaps", ...
    "No complete MathWorks ITU digital-map folder was found. The folder " + ...
    "must contain maps.mat, p836.mat, p837.mat, and p840.mat. Set " + ...
    "ItuDigitalMapsFolder or MATLAB_ITU_MAPS_FOLDER; see README.md.");
end

function writeInputTable(request,cfg,outputFolder)
inputs = table(request.LatitudeDeg,request.LongitudeDeg, ...
    request.AntennaDiameterM,request.AntennaHeightAglM, ...
    string(request.Service),string(request.GoesSatellite), ...
    request.BoresightLongitudeDeg,request.ExpectedBoresightElevationDeg, ...
    request.ZaRadiusKm,request.GroundOrthometricHeightM, ...
    request.AntennaOrthometricHeightM,request.GeoidUndulationM, ...
    request.AntennaEllipsoidalHeightM,string(request.DemSource), ...
    request.DemResolutionM,string(request.DemRasterId), ...
    string(request.GeoidModel),request.ProtectionCriterionDb, ...
    cfg.reporting.practicalAvailabilityPercent, ...
    request.BeamEirpDensityDbwPerMHz, ...
    VariableNames=["LatitudeDeg","LongitudeDeg","AntennaDiameterM", ...
    "AntennaHeightAglM","Service","GoesSatellite", ...
    "BoresightLongitudeDeg","BoresightElevationDeg", ...
    "GeographicZaRadiusKm","GroundOrthometricHeightM", ...
    "AntennaOrthometricHeightM","GeoidUndulationM", ...
    "AntennaEllipsoidalHeightM","DemSource","DemResolutionM", ...
    "DemRasterId","GeoidModel","ProtectionCriterionDb", ...
    "PrimaryAvailabilityPercent","BeamEirpDensityDbwPerMHz"]);
writetable(inputs,fullfile(outputFolder,"user_inputs.csv"));
end

function displayConfiguration(cfg,options)
configuration = table(string(cfg.receiver.serviceCode), ...
    cfg.site.latitudeDeg,cfg.site.longitudeDeg, ...
    string(cfg.site.boresight.satelliteAssignment), ...
    cfg.site.boresight.geoLongitudeDeg,cfg.antenna.diameterM, ...
    cfg.site.antennaFeedHeightAglM,cfg.receiver.centerFrequencyHz/1e6, ...
    cfg.receiver.bandwidthHz/1e6,cfg.receiver.referenceGOverTDbK, ...
    cfg.receiver.noiseTemperatureK,cfg.receiver.noisePowerDbm, ...
    cfg.za.minimumActiveBeamCenterDistanceKm, ...
    cfg.beams.numberPerSatellite,cfg.beams.coneHalfAngleDeg, ...
    cfg.rf.maximumBeamEirpDensityDbwPerMHz, ...
    cfg.receiver.protectionCriterionDb, ...
    cfg.reporting.practicalAvailabilityPercent, ...
    options.InitialWindowCount,options.MinimumWindowCount, ...
    options.MaximumWindowCount, ...
    VariableNames=["Service","LatitudeDeg","LongitudeDeg", ...
    "GoesSatellite","BoresightLongitudeDeg","AntennaDiameterM", ...
    "AntennaHeightAglM","CenterFrequencyMHz","ReceiverBandwidthMHz", ...
    "SiteGOverTDbK","NoiseTemperatureK","NoisePowerDbm", ...
    "GeographicZaRadiusKm","BeamsPerSatellite", ...
    "FieldOfRegardHalfAngleDeg","MaximumBeamEirpDensityDbwPerMHz", ...
    "ProtectionCriterionDb","PrimaryAvailabilityPercent", ...
    "InitialWindows","MinimumWindows","MaximumWindows"]);
disp(configuration);
end
