function results = runOdsEnsemble(baseConfig,options)
%runOdsEnsemble - Run a phase-diverse ODS angle ensemble
%   RESULTS = runOdsEnsemble(CONFIG) runs one fully resolved protected-site
%   configuration over distributed UTC windows. Samples are pooled within
%   each Monte Carlo realization before one inner/outer angle pair is
%   selected.
%
%   RESULTS = runOdsEnsemble(CONFIG,Name=VALUE) also controls the ensemble
%   duration, convergence test, reproducible seeds, and checkpoint policy.

arguments
    baseConfig (1,1) struct
    options.OutputFolder (1,1) string = ""
    options.InitialWindowCount (1,1) double ...
        {mustBeInteger,mustBePositive} = 12
    options.MinimumWindowCount (1,1) double ...
        {mustBeInteger,mustBePositive} = 24
    options.MaximumWindowCount (1,1) double ...
        {mustBeInteger,mustBePositive} = 48
    options.WindowBatchSize (1,1) double ...
        {mustBeInteger,mustBePositive} = 4
    options.ConvergenceToleranceDeg (1,1) double ...
        {mustBeFinite,mustBePositive} = 1
    options.RequiredStableBatches (1,1) double ...
        {mustBeInteger,mustBePositive} = 2
    options.FineHalfWidthDeg (1,1) double ...
        {mustBeFinite,mustBePositive} = 10
    options.ReferenceEpoch (1,1) datetime = datetime(2026,8,1,0,0,0, ...
        TimeZone="UTC")
    options.TimeStepSec (1,1) double {mustBeFinite,mustBePositive} = 2
    options.WindowDurationSec (1,1) double ...
        {mustBeFinite,mustBePositive} = 7200
    options.WarmupSec (1,1) double {mustBeFinite,mustBeNonnegative} = 120
    options.FutureGuardSec (1,1) double ...
        {mustBeFinite,mustBeNonnegative} = 16
    options.MonteCarloRuns (1,1) double ...
        {mustBeInteger,mustBePositive} = 4
    options.BaseGeometrySeed (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 16751695
    options.BaseTrafficSeed (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 91675169
    options.LatticeDitherAmplitudeDeg (1,1) double ...
        {mustBeFinite,mustBeNonnegative} = 0
    options.SaveCheckpoints (1,1) logical = false
end

requiredConfigFields = ["meta","site","receiver","antenna","beams", ...
    "resources","rf","propagation","reporting","simulation", ...
    "search","output"];
assert(all(isfield(baseConfig,requiredConfigFields)), ...
    "ODS:EnsembleConfig","CONFIG is not a complete ODS configuration.");
if strlength(strtrim(options.OutputFolder)) == 0
    options.OutputFolder = string(baseConfig.output.folder);
end
baseConfig.output.folder = options.OutputFolder;

assert(options.InitialWindowCount >= 12 && ...
    mod(options.InitialWindowCount,options.WindowBatchSize) == 0, ...
    "ODS:InitialEnsembleWindows", ...
    "InitialWindowCount must be at least 12 and divisible by WindowBatchSize.");
assert(options.MinimumWindowCount >= options.InitialWindowCount && ...
    mod(options.MinimumWindowCount,options.WindowBatchSize) == 0, ...
    "ODS:MinimumEnsembleWindows", ...
    "MinimumWindowCount must be at least the initial count and divisible by WindowBatchSize.");
assert(options.MaximumWindowCount >= options.InitialWindowCount && ...
    mod(options.MaximumWindowCount,options.WindowBatchSize) == 0, ...
    "ODS:MaximumEnsembleWindows", ...
    "MaximumWindowCount must be at least the initial count and divisible by the batch size.");
assert(options.MaximumWindowCount >= options.MinimumWindowCount, ...
    "ODS:MaximumEnsembleWindows", ...
    "MaximumWindowCount must be at least MinimumWindowCount.");
assert(options.LatticeDitherAmplitudeDeg == 0, ...
    "ODS:EnsembleLatticeTranslation", ...
    "The validated tightly packed layout permits rigid 0-360 degree " + ...
    "orientation/phase rotation, but not an XY translation that could " + ...
    "violate non-overlap or the 60-degree field-of-regard boundary.");

projectFolder = string(fileparts(mfilename("fullpath")));
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(projectFolder,fullfile(projectFolder,"config"), ...
    fullfile(projectFolder,"src"));
if ~isfolder(options.OutputFolder), mkdir(options.OutputFolder); end
validateOdsConfig(baseConfig);
requiredPredictionGuardSec = baseConfig.ods.commandLatencySec + ...
    baseConfig.ods.clockErrorSec;
assert(options.FutureGuardSec >= requiredPredictionGuardSec, ...
    "ODS:PredictionGuard", ...
    "FutureGuardSec must be at least %.6g s to cover command latency and " + ...
    "clock allowance.",requiredPredictionGuardSec);
assert(~isnat(options.ReferenceEpoch) && ...
    strlength(string(options.ReferenceEpoch.TimeZone)) > 0, ...
    "ODS:ReferenceEpochTimeZone", ...
    "ReferenceEpoch must have an explicit time zone; UTC is recommended.");

plan = buildOdsEnsemblePlan( ...
    ReferenceEpoch=options.ReferenceEpoch, ...
    WindowCount=options.MaximumWindowCount, ...
    WindowDurationSec=options.WindowDurationSec, ...
    TimeStepSec=options.TimeStepSec,WarmupSec=options.WarmupSec, ...
    FutureGuardSec=options.FutureGuardSec, ...
    BaseGeometrySeed=options.BaseGeometrySeed, ...
    BaseTrafficSeed=options.BaseTrafficSeed);
writetable(plan.windows,fullfile(options.OutputFolder,"window_manifest.csv"));

states = initializeCase(baseConfig,options,plan);
fprintf("\nGOES DCS/GRB ODS phase-diverse ensemble\n");
fprintf("  Common forcing: %s\n",plan.forcingId);
fprintf("  Initial exposure: %d x %.1f h = %.1f h per realization\n", ...
    options.InitialWindowCount,options.WindowDurationSec/3600, ...
    options.InitialWindowCount*options.WindowDurationSec/3600);
fprintf("  Site: %s\n",baseConfig.site.name);
fprintf("  Service: %s\n",baseConfig.receiver.serviceCode);
fprintf("  GOES boresight: %s\n", ...
    baseConfig.site.boresight.satelliteAssignment);
fprintf("  Geographic ZA: %.6g km\n", ...
    baseConfig.za.minimumActiveBeamCenterDistanceKm);

% Stage 1: a pooled coarse search across the complete initial 24-hour
% exposure.  No per-window ODS pair is ever selected or averaged.
fprintf("\nStage 1 of 2: pooled coarse search.\n");
[states,memoryLog] = processWindows(states,plan, ...
    1:options.InitialWindowCount,"coarse",table());
saveStageCheckpoint(states,plan,memoryLog,"coarse", ...
    options.InitialWindowCount,options.OutputFolder, ...
    options.SaveCheckpoints);
states = configureFineSearches(states,options.FineHalfWidthDeg);

% Stage 2: pooled half-degree search around both the strict and practical
% coarse optima.  The accumulators retain per-window sufficient statistics
% so convergence can be audited over common prefixes.
fprintf("\nStage 2 of 2: pooled half-degree search.\n");
[states,memoryLog] = processWindows(states,plan, ...
    1:options.InitialWindowCount,"fine",memoryLog);
[states,memoryLog] = ensureFineSearchCoverage(states,plan, ...
    options.InitialWindowCount,memoryLog);
saveStageCheckpoint(states,plan,memoryLog,"fine", ...
    options.InitialWindowCount,options.OutputFolder, ...
    options.SaveCheckpoints);
[convergenceHistory,converged,selectedWindowCount] = ...
    evaluateConvergence(states,options.InitialWindowCount,options);

nextStart = options.InitialWindowCount + 1;
while ~converged && nextStart <= options.MaximumWindowCount
    nextEnd = min(options.MaximumWindowCount, ...
        nextStart + options.WindowBatchSize - 1);
    fprintf("Angles not yet stable; adding common windows %d-%d.\n", ...
        nextStart,nextEnd);
    [states,memoryLog] = processWindows(states,plan,nextStart:nextEnd, ...
        "fine",memoryLog);
    [states,memoryLog] = ensureFineSearchCoverage(states,plan, ...
        nextEnd,memoryLog);
    saveStageCheckpoint(states,plan,memoryLog,"fine",nextEnd, ...
        options.OutputFolder,options.SaveCheckpoints);
    [convergenceHistory,converged,selectedWindowCount] = ...
        evaluateConvergence(states,nextEnd,options);
    nextStart = nextEnd + 1;
end

[resultsTable,searchTables] = finalizeCases(states,selectedWindowCount, ...
    converged,plan);
writetable(resultsTable,fullfile(options.OutputFolder,"ods_results.csv"));
writetable(convergenceHistory,fullfile(options.OutputFolder, ...
    "convergence_history.csv"));
writetable(memoryLog,fullfile(options.OutputFolder,"memory_log.csv"));
writeWorkbook(resultsTable,convergenceHistory,plan,memoryLog, ...
    selectedWindowCount,options.OutputFolder);
writeCaseArtifacts(states,resultsTable,searchTables,selectedWindowCount, ...
    plan,options);
plotConvergence(convergenceHistory,options.OutputFolder);
writeAssumptions(states(1).fineCfg,plan,selectedWindowCount,converged, ...
    options,options.OutputFolder);
[statusText,statusNote] = resultStatus(resultsTable,converged);
writeRunReport(resultsTable,statusText,statusNote,options.OutputFolder);
save(fullfile(options.OutputFolder,"ods_ensemble_results.mat"), ...
    "resultsTable","convergenceHistory","plan","memoryLog","options", ...
    "selectedWindowCount","converged","statusText","statusNote");

fprintf("\nCompleted the site case using %d windows (%.1f pooled hours).\n", ...
    selectedWindowCount,selectedWindowCount*options.WindowDurationSec/3600);
fprintf("Status: %s (%.2f-deg convergence tolerance).\n", ...
    statusText,options.ConvergenceToleranceDeg);
disp(resultsTable(:,["Site","Service","GoesSatellite", ...
    "ZaRadiusKm","OuterAngleDeg", ...
    "InnerAngleDeg","RobustExceedancePercent","Feasible"]));
fprintf("Output folder: %s\n",options.OutputFolder);
results = struct;
results.summary = resultsTable;
results.primary = struct( ...
    "outerAngleDeg",resultsTable.OuterAngleDeg(1), ...
    "innerAngleDeg",resultsTable.InnerAngleDeg(1), ...
    "robustExceedancePercent", ...
    resultsTable.RobustExceedancePercent(1), ...
    "percentileIOverNDb",resultsTable.PercentileIOverNDb(1), ...
    "feasible",resultsTable.Feasible(1));
results.convergenceHistory = convergenceHistory;
results.windowManifest = plan.windows(1:selectedWindowCount,:);
results.forcingId = plan.forcingId;
results.converged = converged;
results.status = statusText;
results.outputFolder = options.OutputFolder;
clear pathCleanup
end

function saveStageCheckpoint(states,plan,memoryLog,stage,windowCount, ...
    outputRoot,saveCheckpoints)
if ~saveCheckpoints
    return
end
checkpointFile = fullfile(outputRoot,compose( ...
    "checkpoint_%s_%03d_windows.mat",stage,windowCount));
save(checkpointFile,"states","plan","memoryLog","stage", ...
    "windowCount","-v7.3");
end

function states = initializeCase(baseConfig,options,plan)
stateTemplate = struct("siteIndex",0,"zaRadiusKm",0,"baseCfg",struct(), ...
    "fineCfg",struct(),"coarseAccumulator",[],"fineAccumulator",[], ...
    "coarseStrict",table(),"coarsePractical",table(), ...
    "fineHalfWidthDeg",NaN,"fineExpansionPass",0, ...
    "visibleSkyLimitDeg",NaN,"peakGeometryBytes",0);
states = stateTemplate;
cfg = baseConfig;
cfg.meta.modelName = "GOES DCS/GRB ODS Angle Simulator";
cfg.meta.modelVersion = "1.0.0";
cfg.meta.releaseId = "GOES-DCS-GRB-ODS-ANGLE-SIMULATOR-1.0.0";
cfg.meta.experimentId = "SITE-ENSEMBLE-" + ...
    upper(string(cfg.site.siteId));
cfg.meta.caseName = string(cfg.meta.caseName) + " | phase-diverse ensemble";
cfg.simulation.timeStepSec = options.TimeStepSec;
cfg.simulation.monteCarloRuns = options.MonteCarloRuns;
cfg.simulation.randomSeed = options.BaseTrafficSeed;
cfg.output.writeDetailedTimeSeries = false;
cfg.output.folder = options.OutputFolder;
cfg.ensemble.enabled = true;
cfg.ensemble.referenceEpoch = plan.referenceEpoch;
cfg.ensemble.geometrySeed = options.BaseGeometrySeed;
cfg.ensemble.windowId = 1;
cfg.ensemble.analysisStartTime = plan.windows.StartTimeUtc(1);
cfg.ensemble.analysisDuration = seconds(plan.windowDurationSec);
cfg.ensemble.guardBeforeSec = plan.warmupSec;
cfg.ensemble.guardAfterSec = plan.futureGuardSec;
cfg.ensemble.latticeRotationEnabled = true;
cfg.ensemble.latticeDitherAmplitudeDeg = ...
    options.LatticeDitherAmplitudeDeg;
cfg.ensemble.latticeDitherIntervalSec = 0;
cfg.ensemble.latticePolicy = ...
    "Service-neutral rigid layout rotation keyed by geometry seed, satellite, and global orbital revolution; stable beam IDs; no demand-driven steering";
cfg.ensemble.forcingId = plan.forcingId;
cfg.ensemble.maximumWindows = options.MaximumWindowCount;
states.siteIndex = 1;
states.zaRadiusKm = cfg.za.minimumActiveBeamCenterDistanceKm;
states.baseCfg = cfg;
end

function [states,memoryLog] = processWindows(states,plan,windowIndices, ...
    stage,memoryLog)
siteCount = size(states,1);
zaCount = size(states,2);
for siteIdx = 1:siteCount
    siteName = states(siteIdx,1).baseCfg.site.name;
    for windowIdx = windowIndices
        window = plan.windows(windowIdx,:);
        if stage == "coarse"
            geometryCfg = states(siteIdx,1).baseCfg;
        else
            geometryCfg = states(siteIdx,1).fineCfg;
        end
        geometryCfg = configureWindow(geometryCfg,window,plan);
        fprintf("  %s | %s | window %d/%d (%s UTC)\n", ...
            upper(stage),siteName,windowIdx,height(plan.windows), ...
            string(window.StartTimeUtc,"yyyy-MM-dd HH:mm"));
        geometry = buildConstellationGeometry(geometryCfg);
        geometryInfo = whos("geometry");
        geometryBytes = geometryInfo.bytes;
        assert(nnz(geometry.analysisMask) == plan.coreSamplesPerWindow, ...
            "ODS:EnsembleCoreSamples", ...
            "Window %d produced %d core samples; expected %d.", ...
            windowIdx,nnz(geometry.analysisMask),plan.coreSamplesPerWindow);
        memoryRow = table(stage,siteName,windowIdx, ...
            geometryBytes,geometryBytes/2^20, ...
            VariableNames=["Stage","Site","WindowId", ...
            "GeometryBytes","GeometryMiB"]);
        if width(memoryLog) == 0
            memoryLog = memoryRow;
        else
            memoryLog = [memoryLog; memoryRow]; %#ok<AGROW>
        end
        for zaIdx = 1:zaCount
            if stage == "coarse"
                cfg = states(siteIdx,zaIdx).baseCfg;
                accumulatorField = "coarseAccumulator";
            else
                cfg = states(siteIdx,zaIdx).fineCfg;
                accumulatorField = "fineAccumulator";
            end
            cfg = configureWindow(cfg,window,plan);
            geometryZa = geometryForZa(geometry,cfg, ...
                states(siteIdx,zaIdx).zaRadiusKm);
            realizations = buildOdsRealizations(cfg,geometryZa, ...
                RandomSeed=window.TrafficSeed);
            context = buildStreamingOdsCandidateContext( ...
                cfg,geometryZa,realizations);
            if isempty(states(siteIdx,zaIdx).(accumulatorField))
                states(siteIdx,zaIdx).(accumulatorField) = ...
                    initializeStreamingOdsAccumulator(cfg,context);
            end
            states(siteIdx,zaIdx).(accumulatorField) = ...
                accumulateStreamingOdsWindow(cfg, ...
                states(siteIdx,zaIdx).(accumulatorField),context);
            states(siteIdx,zaIdx).visibleSkyLimitDeg = ...
                geometry.summary.visibleSkyMaximumSeparationDeg;
            states(siteIdx,zaIdx).peakGeometryBytes = max( ...
                states(siteIdx,zaIdx).peakGeometryBytes,geometryBytes);
            clear geometryZa realizations context
        end
        clear geometry
    end
end
end

function cfg = configureWindow(cfg,window,plan)
cfg.simulation.startTime = window.GuardStartTimeUtc;
cfg.simulation.duration = window.GuardEndTimeUtc - ...
    window.GuardStartTimeUtc;
cfg.simulation.randomSeed = window.TrafficSeed;
cfg.ensemble.enabled = true;
cfg.ensemble.referenceEpoch = plan.referenceEpoch;
cfg.ensemble.geometrySeed = window.GeometrySeed;
cfg.ensemble.windowId = window.WindowId;
cfg.ensemble.analysisStartTime = window.StartTimeUtc;
cfg.ensemble.analysisDuration = seconds(plan.windowDurationSec);
cfg.ensemble.guardBeforeSec = plan.warmupSec;
cfg.ensemble.guardAfterSec = plan.futureGuardSec;
cfg.ensemble.forcingId = plan.forcingId;
end

function geometry = geometryForZa(baseGeometry,cfg,zaRadiusKm)
geometry = baseGeometry;
geometry.zaAllowedBeam = ...
    geometry.beamCenterGroundSeparationKm >= zaRadiusKm;
visible = geometry.visible;
timeCount = size(visible,1);
satelliteCount = size(visible,2);
cochannelAllowed = geometry.zaAllowedBeam(:,:, ...
    cfg.resources.cochannelBeamIndices);
geometry.summary.cochannelBeamZaBlockedPercent = 100 * ...
    nnz(~cochannelAllowed & reshape(visible,timeCount,satelliteCount,1)) / ...
    max(1,nnz(repmat(visible,1,1, ...
    numel(cfg.resources.cochannelBeamIndices))));
geometry.summary.zaMinimumBeamCenterDistanceKm = zaRadiusKm;
end

function states = configureFineSearches(states,halfWidthDeg)
for siteIdx = 1:size(states,1)
    for zaIdx = 1:size(states,2)
        cfg = states(siteIdx,zaIdx).baseCfg;
        [~,strictRow,practicalRow] = finalizeStreamingOdsSearch( ...
            cfg,states(siteIdx,zaIdx).coarseAccumulator);
        states(siteIdx,zaIdx).coarseStrict = strictRow;
        states(siteIdx,zaIdx).coarsePractical = practicalRow;
        visibleLimitDeg = states(siteIdx,zaIdx).visibleSkyLimitDeg;
        cfg.search.outerAngleRangeDeg = combinedGrid( ...
            [strictRow.OuterAngleDeg practicalRow.OuterAngleDeg], ...
            halfWidthDeg,0.5,visibleLimitDeg);
        cfg.search.innerAngleRangeDeg = combinedGrid( ...
            [strictRow.InnerAngleDeg practicalRow.InnerAngleDeg], ...
            halfWidthDeg,0.5,visibleLimitDeg);
        cfg.search.adaptiveRefinementEnabled = false;
        states(siteIdx,zaIdx).fineCfg = cfg;
        states(siteIdx,zaIdx).fineHalfWidthDeg = halfWidthDeg;
    end
end
end

function values = combinedGrid(centers,halfWidth,step,limit)
centers = centers(isfinite(centers));
assert(~isempty(centers),"ODS:FineSearchCenters", ...
    "At least one finite coarse-search center is required.");
lower = max(0,step*floor((min(centers)-halfWidth)/step));
upper = min(limit,step*ceil((max(centers)+halfWidth)/step));
values = unique([0 lower:step:upper centers limit]);
values = values(values >= 0 & values <= limit);
end

function [states,memoryLog] = ensureFineSearchCoverage( ...
    states,plan,windowCount,memoryLog)
% Expand and deterministically replay if the selected result reaches a
% nonphysical edge of the local fine-search band.  This prevents an
% arbitrary +/-FineHalfWidthDeg band from masquerading as a solution.
maximumPasses = 6;
while fineSearchNeedsExpansion(states,windowCount)
    priorHalfWidth = states(1).fineHalfWidthDeg;
    visibleLimit = max([states.visibleSkyLimitDeg]);
    nextHalfWidth = min(visibleLimit,max(priorHalfWidth + 10, ...
        2*priorHalfWidth));
    if nextHalfWidth <= priorHalfWidth + eps(max(1,priorHalfWidth))
        warning("ODS:FineSearchPhysicalLimit", ...
            "The fine search reached the physical visible-sky limit.");
        break
    end
    expansionPass = states(1).fineExpansionPass + 1;
    assert(expansionPass <= maximumPasses,"ODS:FineSearchExpansion", ...
        "The fine search still reached a local grid edge after %d expansions.", ...
        maximumPasses);
    fprintf("Fine-search result reached a local grid edge; " + ...
        "expanding half-width from %.1f to %.1f deg and replaying %d windows.\n", ...
        priorHalfWidth,nextHalfWidth,windowCount);
    states = configureFineSearches(states,nextHalfWidth);
    for stateIdx = 1:numel(states)
        states(stateIdx).fineAccumulator = [];
        states(stateIdx).fineExpansionPass = expansionPass;
    end
    [states,memoryLog] = processWindows(states,plan,1:windowCount, ...
        "fine_replay",memoryLog);
end
end

function tf = fineSearchNeedsExpansion(states,windowCount)
tf = false;
for stateIdx = 1:numel(states)
    cfg = states(stateIdx).fineCfg;
    [~,strictRow,practicalRow] = finalizeStreamingOdsSearch( ...
        cfg,states(stateIdx).fineAccumulator,windowCount);
    if cfg.reporting.primaryResult == "strict"
        row = strictRow;
    else
        row = practicalRow;
    end
    tf = tf || isNonphysicalGridEdge(row.OuterAngleDeg, ...
        cfg.search.outerAngleRangeDeg,states(stateIdx).visibleSkyLimitDeg) || ...
        isNonphysicalGridEdge(row.InnerAngleDeg, ...
        cfg.search.innerAngleRangeDeg,states(stateIdx).visibleSkyLimitDeg);
end
end

function tf = isNonphysicalGridEdge(value,grid,visibleLimitDeg)
tolerance = 1e-8;
fineStepDeg = 0.5;
if abs(value) <= tolerance || ...
        abs(value-visibleLimitDeg) <= tolerance
    tf = false;
    return
end
grid = sort(unique(grid(:)));
lower = grid(grid < value-tolerance);
upper = grid(grid > value+tolerance);
missingLowerNeighbor = isempty(lower) || ...
    value-lower(end) > fineStepDeg+tolerance;
missingUpperNeighbor = isempty(upper) || ...
    upper(1)-value > fineStepDeg+tolerance;
tf = missingLowerNeighbor || missingUpperNeighbor;
end

function [history,converged,selectedWindowCount] = ...
    evaluateConvergence(states,availableWindowCount,options)
checkpoints = options.WindowBatchSize:options.WindowBatchSize: ...
    availableWindowCount;
rows = cell(0,1);
priorAngles = [];
consecutiveStable = 0;
converged = false;
selectedWindowCount = availableWindowCount;
for checkpoint = checkpoints
    currentAngles = zeros(numel(states),2);
    caseLinearIdx = 0;
    checkpointRows = cell(0,1);
    allPrimaryFeasible = true;
    allSearchesResolved = true;
    for siteIdx = 1:size(states,1)
        for zaIdx = 1:size(states,2)
            caseLinearIdx = caseLinearIdx + 1;
            cfg = states(siteIdx,zaIdx).fineCfg;
            [~,~,practicalRow,~,poolSummary] = ...
                finalizeStreamingOdsSearch(cfg, ...
                states(siteIdx,zaIdx).fineAccumulator,checkpoint);
            currentAngles(caseLinearIdx,:) = [ ...
                practicalRow.OuterAngleDeg practicalRow.InnerAngleDeg];
            if isempty(priorAngles)
                outerDeltaDeg = NaN;
                innerDeltaDeg = NaN;
            else
                outerDeltaDeg = abs(currentAngles(caseLinearIdx,1) - ...
                    priorAngles(caseLinearIdx,1));
                innerDeltaDeg = abs(currentAngles(caseLinearIdx,2) - ...
                    priorAngles(caseLinearIdx,2));
            end
            allPrimaryFeasible = allPrimaryFeasible && ...
                logical(practicalRow.PracticalFeasible);
            allSearchesResolved = allSearchesResolved && ...
                ~isNonphysicalGridEdge(practicalRow.OuterAngleDeg, ...
                cfg.search.outerAngleRangeDeg, ...
                states(siteIdx,zaIdx).visibleSkyLimitDeg) && ...
                ~isNonphysicalGridEdge(practicalRow.InnerAngleDeg, ...
                cfg.search.innerAngleRangeDeg, ...
                states(siteIdx,zaIdx).visibleSkyLimitDeg);
            exceedanceMarginPercent = ...
                cfg.reporting.practicalAllowedExceedancePercent - ...
                practicalRow.RobustExceedancePercent;
            checkpointRows{end+1,1} = table(checkpoint, ...
                string(cfg.site.name),states(siteIdx,zaIdx).zaRadiusKm, ...
                practicalRow.OuterAngleDeg,practicalRow.InnerAngleDeg, ...
                outerDeltaDeg,innerDeltaDeg, ...
                practicalRow.RobustExceedancePercent, ...
                exceedanceMarginPercent, ...
                practicalRow.PracticalPercentileIOverNDb, ...
                logical(practicalRow.PracticalFeasible), ...
                poolSummary.samplesPerRun(1), ...
                VariableNames=["WindowCount","Site","ZaRadiusKm", ...
                "OuterAngleDeg","InnerAngleDeg","OuterDeltaDeg", ...
                "InnerDeltaDeg","RobustExceedancePercent", ...
                "ExceedanceMarginPercent","PercentileIOverNDb", ...
                "Feasible","PooledSamplesPerRun"]); %#ok<AGROW>
        end
    end
    if isempty(priorAngles)
        globalMaximumAngleChangeDeg = NaN;
    else
        globalMaximumAngleChangeDeg = max(abs(currentAngles-priorAngles), ...
            [],"all");
        if globalMaximumAngleChangeDeg <= ...
                options.ConvergenceToleranceDeg && allPrimaryFeasible && ...
                allSearchesResolved
            consecutiveStable = consecutiveStable + 1;
        else
            consecutiveStable = 0;
        end
    end
    checkpointTable = vertcat(checkpointRows{:});
    checkpointTable.GlobalMaximumAngleChangeDeg(:) = ...
        globalMaximumAngleChangeDeg;
    checkpointTable.ConsecutiveStableBatches(:) = consecutiveStable;
    checkpointTable.SearchResolved(:) = allSearchesResolved;
    checkpointTable.Converged(:) = checkpoint >= ...
        options.MinimumWindowCount && consecutiveStable >= ...
        options.RequiredStableBatches;
    rows{end+1,1} = checkpointTable; %#ok<AGROW>
    if checkpointTable.Converged(1)
        converged = true;
        selectedWindowCount = checkpoint;
        break
    end
    priorAngles = currentAngles;
end
history = vertcat(rows{:});
end

function [resultsTable,searchTables] = finalizeCases( ...
    states,windowCount,converged,plan)
rows = cell(0,1);
searchTables = cell(size(states));
for siteIdx = 1:size(states,1)
    for zaIdx = 1:size(states,2)
        cfg = states(siteIdx,zaIdx).fineCfg;
        [searchTable,strictRow,practicalRow,baseline,poolSummary] = ...
            finalizeStreamingOdsSearch(cfg, ...
            states(siteIdx,zaIdx).fineAccumulator,windowCount);
        searchTables{siteIdx,zaIdx} = searchTable;
        if cfg.reporting.primaryResult == "strict"
            primaryRow = strictRow;
            primaryFeasible = strictRow.Feasible;
        else
            primaryRow = practicalRow;
            primaryFeasible = practicalRow.PracticalFeasible;
        end
        fineOuter = cfg.search.outerAngleRangeDeg;
        fineInner = cfg.search.innerAngleRangeDeg;
        searchBoundaryFlag = isNonphysicalGridEdge( ...
            primaryRow.OuterAngleDeg,fineOuter, ...
            states(siteIdx,zaIdx).visibleSkyLimitDeg) || ...
            isNonphysicalGridEdge(primaryRow.InnerAngleDeg,fineInner, ...
            states(siteIdx,zaIdx).visibleSkyLimitDeg);
        innerAtPhysicalMinimum = abs(primaryRow.InnerAngleDeg) < 1e-8;
        outerAtVisibleSkyLimit = abs(primaryRow.OuterAngleDeg - ...
            states(siteIdx,zaIdx).visibleSkyLimitDeg) < 1e-8;
        rows{end+1,1} = table(string(cfg.site.name), ...
            cfg.site.latitudeDeg,cfg.site.longitudeDeg, ...
            string(cfg.receiver.serviceCode), ...
            string(cfg.site.boresight.satelliteAssignment), ...
            states(siteIdx,zaIdx).zaRadiusKm, ...
            cfg.antenna.diameterM,cfg.site.antennaFeedHeightAglM, ...
            cfg.rf.maximumBeamEirpDensityDbwPerMHz, ...
            cfg.receiver.protectionCriterionDb, ...
            cfg.reporting.practicalAvailabilityPercent, ...
            primaryRow.OuterAngleDeg,primaryRow.InnerAngleDeg, ...
            primaryRow.RobustExceedancePercent, ...
            primaryRow.PracticalPercentileIOverNDb, ...
            primaryRow.MaximumIOverNDb,logical(primaryFeasible), ...
            strictRow.OuterAngleDeg,strictRow.InnerAngleDeg, ...
            strictRow.WorstExceedancePercent, ...
            practicalRow.OuterAngleDeg,practicalRow.InnerAngleDeg, ...
            practicalRow.RetaskDutyPercent, ...
            practicalRow.ShutdownDutyPercent, ...
            baseline.robustExceedancePercent, ...
            windowCount,windowCount*plan.windowDurationSec/3600, ...
            poolSummary.samplesPerRun(1),plan.forcingId, ...
            logical(converged),logical(searchBoundaryFlag), ...
            logical(innerAtPhysicalMinimum), ...
            logical(outerAtVisibleSkyLimit), ...
            states(siteIdx,zaIdx).peakGeometryBytes/2^20, ...
            string(cfg.meta.modelVersion), ...
            VariableNames=["Site","LatitudeDeg","LongitudeDeg", ...
            "Service","GoesSatellite","ZaRadiusKm","AntennaDiameterM", ...
            "AntennaHeightAglM","PerBeamEirpDensityDbwPerMHz", ...
            "ProtectionCriterionDb","AvailabilityPercent", ...
            "OuterAngleDeg","InnerAngleDeg", ...
            "RobustExceedancePercent","PercentileIOverNDb", ...
            "MaximumIOverNDb","Feasible","StrictOuterAngleDeg", ...
            "StrictInnerAngleDeg","StrictWorstExceedancePercent", ...
            "PracticalOuterAngleDeg","PracticalInnerAngleDeg", ...
            "RetaskDutyPercent","ShutdownDutyPercent", ...
            "UnmitigatedRobustExceedancePercent","WindowCount", ...
            "PooledExposureHours","PooledSamplesPerRun","ForcingId", ...
            "Converged","SearchBoundaryFlag","InnerAtPhysicalMinimum", ...
            "OuterAtVisibleSkyLimit","PeakGeometryMiB", ...
            "ModelVersion"]); %#ok<AGROW>
    end
end
resultsTable = vertcat(rows{:});
resultsTable = sortrows(resultsTable,["Site","ZaRadiusKm"]);
end

function writeCaseArtifacts(states,resultsTable,searchTables,windowCount, ...
    plan,options)
for siteIdx = 1:size(states,1)
    for zaIdx = 1:size(states,2)
        cfg = states(siteIdx,zaIdx).fineCfg;
        caseFolder = string(cfg.output.folder);
        if ~isfolder(caseFolder), mkdir(caseFolder); end
        match = resultsTable.Site == string(cfg.site.name) & ...
            resultsTable.ZaRadiusKm == states(siteIdx,zaIdx).zaRadiusKm;
        writetable(resultsTable(match,:),fullfile(caseFolder,"result.csv"));
        writetable(searchTables{siteIdx,zaIdx}, ...
            fullfile(caseFolder,"pooled_angle_search.csv"));
        caseManifest = plan.windows(1:windowCount,:);
        writetable(caseManifest,fullfile(caseFolder,"window_manifest.csv"));
        cfg.ensemble.completedWindowCount = windowCount;
        cfg.ensemble.pooledExposureHours = ...
            windowCount*plan.windowDurationSec/3600;
        cfg.ensemble.convergenceToleranceDeg = ...
            options.ConvergenceToleranceDeg;
        jsonCfg = jsonSafeConfiguration(cfg);
        fid = fopen(fullfile(caseFolder,"configuration.json"),"w");
        assert(fid >= 0,"ODS:EnsembleConfigWrite", ...
            "Could not write configuration.json in %s.",caseFolder);
        cleanup = onCleanup(@() fclose(fid));
        fprintf(fid,"%s",jsonencode(jsonCfg,PrettyPrint=true));
        clear cleanup
    end
end
end

function jsonCfg = jsonSafeConfiguration(cfg)
jsonCfg = cfg;
jsonCfg.simulation.startTime = char(cfg.simulation.startTime, ...
    "yyyy-MM-dd'T'HH:mm:ssXXX");
jsonCfg.simulation.durationSeconds = seconds(cfg.simulation.duration);
jsonCfg.simulation = rmfield(jsonCfg.simulation,"duration");
if isfield(jsonCfg,"ensemble")
    jsonCfg.ensemble.referenceEpoch = char(cfg.ensemble.referenceEpoch, ...
        "yyyy-MM-dd'T'HH:mm:ssXXX");
    jsonCfg.ensemble.analysisStartTime = char( ...
        cfg.ensemble.analysisStartTime,"yyyy-MM-dd'T'HH:mm:ssXXX");
    jsonCfg.ensemble.analysisDurationSeconds = seconds( ...
        cfg.ensemble.analysisDuration);
    jsonCfg.ensemble = rmfield(jsonCfg.ensemble,"analysisDuration");
end
end

function writeWorkbook(resultsTable,history,plan,memoryLog,windowCount,outputRoot)
workbook = fullfile(outputRoot,"ODS_Angle_Results.xlsx");
writetable(resultsTable,workbook,Sheet="ODS Results");
writetable(history,workbook,Sheet="Convergence");
writetable(plan.windows(1:windowCount,:),workbook,Sheet="Window Manifest");
writetable(memoryLog,workbook,Sheet="Memory Log");
end

function plotConvergence(history,outputRoot)
figureHandle = figure(Visible="off",Color="white",Position=[100 100 900 520]);
cleanup = onCleanup(@() close(figureHandle));
rows = sortrows(history,"WindowCount");
plot(rows.WindowCount,rows.OuterAngleDeg,"-o",LineWidth=1.8, ...
    DisplayName="Outer angle");
hold on;
plot(rows.WindowCount,rows.InnerAngleDeg,"-s",LineWidth=1.8, ...
    DisplayName="Inner angle");
grid on;
xlabel("Pooled two-hour windows");
ylabel("ODS angle from selected GOES boresight (deg)");
title("Multi-window ODS angle convergence");
legend(Location="best");
exportgraphics(figureHandle,fullfile(outputRoot,"ods_angle_convergence.png"), ...
    Resolution=180);
end

function writeAssumptions(cfg,plan,windowCount,converged,options,outputRoot)
if cfg.receiver.serviceCode == "DCS"
    serviceDescription = ...
        "DCS, 1679.9 MHz center, 0.4 MHz bandwidth";
else
    serviceDescription = ...
        "GRB, 1686.6 MHz center, 10.9 MHz bandwidth";
end
parameter = [ ...
    "Model";"Service";"GOES pointing";"Constellation"; ...
    "Satellite spot-beam operation";"Service steering"; ...
    "Per-beam EIRP density";"Visibility";"Receiver antenna pattern"; ...
    "Propagation";"Criterion";"Window design";"Pooling"; ...
    "Common random numbers";"Lattice randomization";"Convergence"; ...
    "Core samples";"Forcing ID"];
value = [ ...
    "GOES DCS/GRB ODS Angle Simulator 1.0.0"; ...
    serviceDescription; ...
    compose("%s at %.6g deg east-positive longitude", ...
    cfg.site.boresight.satelliteAssignment, ...
    cfg.site.boresight.geoLongitudeDeg); ...
    "325 satellites at 340 km/53 deg plus 325 at 355 km/43 deg; anchored two-body Walker geometry"; ...
    "30 tightly packed nonoverlapping steering cells in a 60-deg off-nadir field of regard; each RF spot has a 2-deg half-power radius; four-carrier reuse; all active contributors aggregated"; ...
    "Service-neutral snapshot steering; no demand/user-location steering"; ...
    compose("%.6g dBW/MHz maximum for each active spot", ...
    cfg.rf.maximumBeamEirpDensityDbwPerMHz); ...
    "Geometric local horizon, 0-deg minimum LEO elevation"; ...
    "ITU-R S.580-6/APEREC015 size-dependent pattern without a -27 dBi cutoff"; ...
    "Site-specific ITU-R P.618 atmospheric lookup, ITU-R P.2108 open/rural clutter, free-space spreading, 1-dB implementation loss, and provisional 30-150 km NRAO-informed correction"; ...
    compose("I/N <= %.6g dB at %.6g%% modeled availability", ...
    cfg.receiver.protectionCriterionDb, ...
    cfg.reporting.practicalAvailabilityPercent); ...
    compose("%d noncontiguous %.6g-h UTC windows distributed across days/start times, plus %.6g-s warm-up and %.6g-s future guard", ...
    windowCount,plan.windowDurationSec/3600,plan.warmupSec, ...
    plan.futureGuardSec); ...
    "Raw core samples are pooled within each Monte Carlo realization before one angle pair is selected; window-specific angle results are not averaged"; ...
    "Every cumulative prefix uses the same deterministic epoch plan and seed schedule; all candidates within a run share geometry, traffic, load, and power-error streams"; ...
    "Rigid service-neutral 0-360 deg lattice orientation/phase randomization keyed by geometry seed/satellite/global revolution; XY translation dither is zero to preserve nonoverlap and the 60-deg boundary"; ...
    compose("Cumulative %d-window batches; both primary angles must change <= %.6g deg for %d successive batches after at least %d windows; converged=%s", ...
    options.WindowBatchSize,options.ConvergenceToleranceDeg, ...
    options.RequiredStableBatches, ...
    options.MinimumWindowCount,string(converged)); ...
    compose("%d per realization (%.1f h at %.6g-s resolution)", ...
    windowCount*plan.coreSamplesPerWindow, ...
    windowCount*plan.windowDurationSec/3600,plan.timeStepSec); ...
    plan.forcingId];
assumptions = table(parameter,value,VariableNames=["Parameter","Value"]);
writetable(assumptions,fullfile(outputRoot,"assumptions.csv"));
sourceFiles = table(["evidence/beam_packing_layout.csv"; ...
    "evidence/grb_receiver_profile.csv"; ...
    "evidence/nrao_dtc_calibration.csv"],VariableNames="PackageRelativeFile");
writetable(sourceFiles,fullfile(outputRoot,"evidence_manifest.csv"));
end

function [status,statusNote] = resultStatus(resultsTable,converged)
row = resultsTable(1,:);
if converged
    status = "CONVERGED";
    statusNote = "The primary pair met the protection criterion and the configured angle-stability test.";
else
    status = "PROVISIONAL - MAXIMUM WINDOWS REACHED";
    statusNote = "Do not treat this pair as stable; increase MaximumWindowCount and rerun.";
end
if ~row.Feasible
    status = "NO FEASIBLE PAIR FOUND";
    statusNote = "The reported pair is the least-exceeding search candidate, not a protective solution.";
elseif row.SearchBoundaryFlag
    status = "PROVISIONAL - SEARCH BOUNDARY";
    statusNote = "The selected pair reached a nonphysical local search boundary.";
end
end

function writeRunReport(resultsTable,status,statusNote,outputRoot)
row = resultsTable(1,:);
report = [ ...
    "GOES DCS/GRB ODS Angle Simulator"; ...
    "================================"; ...
    ""; ...
    "Status: " + status; ...
    statusNote; ...
    ""; ...
    compose("Site: %s (%.6f, %.6f)",row.Site,row.LatitudeDeg,row.LongitudeDeg); ...
    compose("Service / boresight: %s / %s",row.Service,row.GoesSatellite); ...
    compose("ZA radius: %.6g km",row.ZaRadiusKm); ...
    compose("Outer angle from boresight: %.2f deg",row.OuterAngleDeg); ...
    compose("Inner angle from boresight: %.2f deg",row.InnerAngleDeg); ...
    compose("Robust exceedance: %.6g percent",row.RobustExceedancePercent); ...
    compose("Robust percentile I/N: %.3f dB",row.PercentileIOverNDb); ...
    compose("Pooled exposure: %.1f h per Monte Carlo realization",row.PooledExposureHours); ...
    ""; ...
    "Angles are measured from the selected GOES boresight, not from zenith."; ...
    "This is an engineering sensitivity result, not a coordination determination."];
fid = fopen(fullfile(outputRoot,"run_report.txt"),"w");
assert(fid >= 0,"ODS:RunReportWrite", ...
    "Could not write run_report.txt in %s.",outputRoot);
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,"%s\n",report);
clear cleanup
end
