function heightTable = writeHeightProvenance(heightInfo,outputFolder)
%writeHeightProvenance Save resolved heights and the raw DEM response.

heightTable = table(heightInfo.latitudeDeg,heightInfo.longitudeDeg, ...
    heightInfo.antennaHeightAglM,heightInfo.groundOrthometricHeightM, ...
    heightInfo.antennaOrthometricHeightM,heightInfo.geoidUndulationM, ...
    heightInfo.antennaEllipsoidalHeightM,string(heightInfo.demSource), ...
    heightInfo.demResolutionM,string(heightInfo.demRasterId), ...
    string(heightInfo.geoidModel),string(heightInfo.heightEquation), ...
    VariableNames=["LatitudeDeg","LongitudeDeg","AntennaHeightAglM", ...
    "GroundOrthometricHeightM","AntennaOrthometricHeightM", ...
    "GeoidUndulationM","AntennaEllipsoidalHeightM","DemSource", ...
    "DemResolutionM","DemRasterId","GeoidModel","HeightEquation"]);
writetable(heightTable,fullfile(outputFolder,"site_heights.csv"));

responseFile = fullfile(outputFolder,"dem_response.json");
fileId = fopen(responseFile,"w");
assert(fileId >= 0,"ODS:DemResponseFile", ...
    "Unable to create DEM response file: %s",responseFile);
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId,"%s\n",jsonencode(heightInfo.rawDemResponse,PrettyPrint=true));
clear cleanup
end
