% wallopsDryRunExample
% Resolve and display a Wallops DCS configuration without running P.618 or
% the computationally substantial multi-window ensemble. The DEM elevation
% is a cached example value; replace it with your authoritative value.

projectFolder = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(projectFolder);

results = runOdsAngleSimulator( ...
    SiteName="Wallops example", ...
    LatitudeDeg=37.94651, ...
    LongitudeDeg=-75.46210, ...
    AntennaDiameterM=16.4, ...
    AntennaHeightAglM=5, ...
    Service="DCS", ...
    GoesSatellite="GOES East", ...
    ZaRadiusKm=30, ...
    DemGroundElevationM=9.465678215, ...
    DryRun=true);
