function context = buildStreamingOdsCandidateContext(cfg, geometry, realizations)
%buildStreamingOdsCandidateContext Build one guarded-window ODS cache.
%   CONTEXT = buildStreamingOdsCandidateContext(CFG, GEOMETRY, REALIZATIONS)
%   evaluates ODS hysteresis on every guarded sample, but retains power and
%   count data only where GEOMETRY.analysisMask is true.  The returned
%   context is intentionally limited to one observation window and may be
%   discarded immediately after accumulateStreamingOdsWindow is called.

arguments
    cfg (1,1) struct
    geometry (1,1) struct
    realizations (1,1) struct
end

requiredGeometry = ["analysisMask", "time", "summary"];
for fieldName = requiredGeometry
    assert(isfield(geometry, fieldName), "ODS:StreamingGeometryField", ...
        "Guarded geometry is missing required field '%s'.", fieldName);
end
requiredRealizations = ["preMitigationPowerDbm", ...
    "outerRetaskedPowerDbm", "activeScheduledLink", ...
    "effectiveAngleDeg", "predictedEntryAngleDeg", ...
    "protectionRelevant"];
for fieldName = requiredRealizations
    assert(isfield(realizations, fieldName), ...
        "ODS:StreamingRealizationField", ...
        "Guarded realizations are missing required field '%s'.", fieldName);
end

analysisMask = logical(geometry.analysisMask(:));
timeCount = numel(geometry.time);
assert(numel(analysisMask) == timeCount && any(analysisMask), ...
    "ODS:StreamingAnalysisMask", ...
    "geometry.analysisMask must select at least one of the guarded samples.");
assert(size(realizations.preMitigationPowerDbm, 1) == timeCount, ...
    "ODS:StreamingTimeCount", ...
    "Geometry and realization time dimensions must agree.");

runCount = size(realizations.preMitigationPowerDbm, 3);
assert(runCount == cfg.simulation.monteCarloRuns, ...
    "ODS:StreamingRunCount", ...
    "Realization count differs from cfg.simulation.monteCarloRuns.");
satelliteCount = size(realizations.preMitigationPowerDbm, 2);
expectedSize = [timeCount, satelliteCount, runCount];
assert(isequal(size3(realizations.outerRetaskedPowerDbm), expectedSize) && ...
    isequal(size3(realizations.activeScheduledLink), expectedSize) && ...
    isequal(size3(realizations.effectiveAngleDeg), expectedSize) && ...
    isequal(size3(realizations.predictedEntryAngleDeg), expectedSize), ...
    "ODS:StreamingRealizationSize", ...
    "All guarded realization arrays must have identical T-by-S-by-R size.");
assert(isequal(size(realizations.protectionRelevant), ...
    [timeCount satelliteCount]), "ODS:StreamingProtectionSize", ...
    "realizations.protectionRelevant must be T-by-S.");

visibleSkyLimitDeg = geometry.summary.visibleSkyMaximumSeparationDeg;
searchOuterCandidatesDeg = cfg.search.outerAngleRangeDeg( ...
    cfg.search.outerAngleRangeDeg <= visibleSkyLimitDeg);
if isfield(cfg.ods, "minimumOperationalOuterAngleDeg")
    searchOuterCandidatesDeg = searchOuterCandidatesDeg( ...
        searchOuterCandidatesDeg >= ...
        cfg.ods.minimumOperationalOuterAngleDeg - 1e-10);
end
searchInnerCandidatesDeg = cfg.search.innerAngleRangeDeg( ...
    cfg.search.innerAngleRangeDeg <= visibleSkyLimitDeg);
searchOuterCandidatesDeg = unique([searchOuterCandidatesDeg(:).', ...
    visibleSkyLimitDeg]);
searchInnerCandidatesDeg = unique([searchInnerCandidatesDeg(:).', ...
    visibleSkyLimitDeg]);
outerCandidatesDeg = unique([0 searchOuterCandidatesDeg]);
innerCandidatesDeg = unique([0 searchInnerCandidatesDeg]);

analysisCount = nnz(analysisMask);
outerCount = numel(outerCandidatesDeg);
innerCount = numel(innerCandidatesDeg);
context.schemaVersion = "ODS-STREAMING-CONTEXT-1";
context.searchOuterCandidatesDeg = searchOuterCandidatesDeg;
context.searchInnerCandidatesDeg = searchInnerCandidatesDeg;
context.outerCandidatesDeg = outerCandidatesDeg;
context.innerCandidatesDeg = innerCandidatesDeg;
context.visibleSkyLimitDeg = visibleSkyLimitDeg;
context.noiseDbm = receiverNoiseDbm(cfg);
context.sampleCount = analysisCount;
context.runCount = runCount;
context.totalNormalPowerMw = zeros(analysisCount, runCount);
context.outerNormalPowerMw = zeros(analysisCount, outerCount, runCount);
context.outerRetaskedPowerMw = zeros(analysisCount, outerCount, runCount);
context.innerRetaskedPowerMw = zeros(analysisCount, innerCount, runCount);
context.outerActiveLinkCount = zeros(outerCount, runCount, "uint64");
context.innerActiveLinkCount = zeros(innerCount, runCount, "uint64");
context.activeLinkDenominator = zeros(1, runCount, "uint64");

for runIdx = 1:runCount
    normalPowerMw = 10.^(double( ...
        realizations.preMitigationPowerDbm(:, :, runIdx)) / 10);
    retaskedPowerMw = 10.^(double( ...
        realizations.outerRetaskedPowerDbm(:, :, runIdx)) / 10);
    activeScheduled = logical( ...
        realizations.activeScheduledLink(:, :, runIdx));
    context.totalNormalPowerMw(:, runIdx) = ...
        sum(normalPowerMw(analysisMask, :), 2);
    context.activeLinkDenominator(runIdx) = uint64(nnz( ...
        activeScheduled(analysisMask, :)));

    for candidateIdx = 1:outerCount
        protected = hystereticConeMask( ...
            realizations.effectiveAngleDeg(:, :, runIdx), ...
            realizations.predictedEntryAngleDeg(:, :, runIdx), ...
            realizations.protectionRelevant, ...
            outerCandidatesDeg(candidateIdx), cfg.ods.hysteresisDeg);
        selected = protected(analysisMask, :);
        context.outerNormalPowerMw(:, candidateIdx, runIdx) = ...
            sum(normalPowerMw(analysisMask, :) .* selected, 2);
        context.outerRetaskedPowerMw(:, candidateIdx, runIdx) = ...
            sum(retaskedPowerMw(analysisMask, :) .* selected, 2);
        context.outerActiveLinkCount(candidateIdx, runIdx) = ...
            uint64(nnz(selected & activeScheduled(analysisMask, :)));
    end

    for candidateIdx = 1:innerCount
        protected = hystereticConeMask( ...
            realizations.effectiveAngleDeg(:, :, runIdx), ...
            realizations.predictedEntryAngleDeg(:, :, runIdx), ...
            realizations.protectionRelevant, ...
            innerCandidatesDeg(candidateIdx), cfg.ods.hysteresisDeg);
        selected = protected(analysisMask, :);
        context.innerRetaskedPowerMw(:, candidateIdx, runIdx) = ...
            sum(retaskedPowerMw(analysisMask, :) .* selected, 2);
        context.innerActiveLinkCount(candidateIdx, runIdx) = ...
            uint64(nnz(selected & activeScheduled(analysisMask, :)));
    end
end
end

function protected = hystereticConeMask(angleDeg, entryAngleDeg, ...
    protectionRelevant, thresholdDeg, hysteresisDeg)
% Evaluate the state machine on guards as well as reported samples.

protected = false(size(angleDeg));
priorProtected = false(1, size(angleDeg, 2));
for timeIdx = 1:size(angleDeg, 1)
    currentProtected = protectionRelevant(timeIdx, :) & ( ...
        entryAngleDeg(timeIdx, :) <= thresholdDeg | ...
        (priorProtected & angleDeg(timeIdx, :) <= ...
        thresholdDeg + hysteresisDeg));
    protected(timeIdx, :) = currentProtected;
    priorProtected = currentProtected;
end
end

function noiseDbm = receiverNoiseDbm(cfg)
noiseW = 1.380649e-23 * cfg.receiver.noiseTemperatureK * ...
    cfg.receiver.bandwidthHz;
noiseDbm = 10 * log10(noiseW) + 30;
end

function value = size3(array)
value = [size(array, 1), size(array, 2), size(array, 3)];
end
