function validateOdsConfig(cfg)
%validateOdsConfig Validate required fields and physical relationships.

requiredGroups = ["site", "receiver", "antenna", "constellation", "beams", ...
    "za", "resources", "rf", "propagation", "aggregation", "ods", ...
    "calibration", "uncertainty", "reporting", "simulation", ...
    "search", "output"];
for groupName = requiredGroups
    assert(isfield(cfg, groupName), "ODS:MissingConfigGroup", ...
        "Missing configuration group: %s", groupName);
end

if isfield(cfg,"ensemble") && isfield(cfg.ensemble,"enabled") && ...
        logical(cfg.ensemble.enabled)
    requiredEnsembleFields = ["referenceEpoch","geometrySeed", ...
        "analysisStartTime","analysisDuration"];
    assert(all(isfield(cfg.ensemble,requiredEnsembleFields)), ...
        "ODS:MissingEnsembleField", ...
        "Enabled ensemble geometry is missing a required field.");
    assert(isdatetime(cfg.ensemble.referenceEpoch) && ...
        isscalar(cfg.ensemble.referenceEpoch) && ...
        isdatetime(cfg.ensemble.analysisStartTime) && ...
        isscalar(cfg.ensemble.analysisStartTime) && ...
        isdatetime(cfg.simulation.startTime) && ...
        isscalar(cfg.simulation.startTime), ...
        "ODS:EnsembleEpoch", ...
        "Reference, analysis, and guarded scenario epochs must be datetime scalars.");
    assert(strlength(string(cfg.ensemble.referenceEpoch.TimeZone)) > 0 && ...
        strlength(string(cfg.ensemble.analysisStartTime.TimeZone)) > 0 && ...
        strlength(string(cfg.simulation.startTime.TimeZone)) > 0, ...
        "ODS:EnsembleTimeZone", ...
        "Ensemble epochs must carry explicit time zones.");
    analysisDurationSec = durationValueSeconds( ...
        cfg.ensemble.analysisDuration);
    simulationDurationSec = durationValueSeconds(cfg.simulation.duration);
    timeStepSec = cfg.simulation.timeStepSec;
    assert(isfinite(analysisDurationSec) && analysisDurationSec > 0 && ...
        isfinite(simulationDurationSec) && simulationDurationSec > 0 && ...
        isfinite(timeStepSec) && timeStepSec > 0, ...
        "ODS:EnsembleDuration", ...
        "Ensemble analysis, guarded duration, and time step must be positive.");
    analysisStopTime = cfg.ensemble.analysisStartTime + ...
        seconds(analysisDurationSec);
    simulationStopTime = cfg.simulation.startTime + ...
        seconds(simulationDurationSec);
    guardBeforeSec = seconds(cfg.ensemble.analysisStartTime - ...
        cfg.simulation.startTime);
    guardAfterSec = seconds(simulationStopTime-analysisStopTime);
    gridTolerance = 1e-8;
    assert(guardBeforeSec >= -gridTolerance && ...
        guardAfterSec >= -gridTolerance, ...
        "ODS:EnsembleGuardCoverage", ...
        "The guarded scenario must contain the complete analysis window.");
    assert(abs(guardBeforeSec/timeStepSec - ...
        round(guardBeforeSec/timeStepSec)) <= gridTolerance && ...
        abs(analysisDurationSec/timeStepSec - ...
        round(analysisDurationSec/timeStepSec)) <= gridTolerance && ...
        abs(simulationDurationSec/timeStepSec - ...
        round(simulationDurationSec/timeStepSec)) <= gridTolerance, ...
        "ODS:EnsembleGridAlignment", ...
        "Analysis and guard boundaries must align with the simulation time grid.");
    assert(isfinite(cfg.ensemble.geometrySeed) && ...
        cfg.ensemble.geometrySeed >= 0 && ...
        mod(cfg.ensemble.geometrySeed,1) == 0, ...
        "ODS:EnsembleGeometrySeed", ...
        "The ensemble geometry seed must be a nonnegative integer.");
    if isfield(cfg.ensemble,"latticeRotationEnabled")
        assert(isscalar(cfg.ensemble.latticeRotationEnabled) && ...
            any(double(cfg.ensemble.latticeRotationEnabled) == [0 1]), ...
            "ODS:EnsembleLatticeRotation", ...
            "latticeRotationEnabled must be a scalar logical value.");
    end
    if isfield(cfg.ensemble,"latticeDitherAmplitudeDeg")
        assert(isfinite(cfg.ensemble.latticeDitherAmplitudeDeg) && ...
            cfg.ensemble.latticeDitherAmplitudeDeg == 0, ...
            "ODS:EnsembleRigidLattice", ...
            "This implementation supports rigid azimuthal lattice rotation; " + ...
            "geometric translation/dither must remain zero to preserve the " + ...
            "validated 60-degree packing boundary.");
    end
    if isfield(cfg.ensemble,"guardBeforeSec")
        assert(abs(cfg.ensemble.guardBeforeSec-guardBeforeSec) <= ...
            gridTolerance, "ODS:EnsembleGuardBefore", ...
            "guardBeforeSec is inconsistent with the configured epochs.");
    end
    if isfield(cfg.ensemble,"guardAfterSec")
        assert(abs(cfg.ensemble.guardAfterSec-guardAfterSec) <= ...
            gridTolerance, "ODS:EnsembleGuardAfter", ...
            "guardAfterSec is inconsistent with the configured epochs.");
    end
end

assert(cfg.receiver.bandwidthHz > 0, "ODS:InvalidBandwidth", ...
    "Receiver bandwidth must be positive.");
assert(cfg.receiver.noiseTemperatureK > 0, "ODS:InvalidNoiseTemperature", ...
    "Noise temperature must be positive.");
assert(isfinite(cfg.receiver.referenceGOverTDbK), ...
    "ODS:InvalidGOverT", "The site antenna-system G/T must be finite.");
expectedPeakGainDbi = 10*log10(cfg.antenna.efficiency * ...
    (pi*cfg.antenna.diameterM/(299792458 / ...
    cfg.receiver.centerFrequencyHz))^2);
expectedNoiseTemperatureK = 10^((expectedPeakGainDbi - ...
    cfg.receiver.referenceGOverTDbK)/10);
assert(abs(cfg.receiver.noiseTemperatureK - expectedNoiseTemperatureK) < ...
    1e-9*expectedNoiseTemperatureK, "ODS:GOverTNoiseTemperature", ...
    "Noise temperature must be derived from peak gain and site G/T.");
expectedNoisePowerDbm = 10*log10(1.380649e-23 * ...
    cfg.receiver.noiseTemperatureK * cfg.receiver.bandwidthHz) + 30;
assert(abs(cfg.receiver.noisePowerDbm - expectedNoisePowerDbm) < 1e-10, ...
    "ODS:NoisePower", "Stored receiver noise power is inconsistent with k*T*B.");
assert(cfg.receiver.allowedExceedancePercent >= 0 && ...
    cfg.receiver.allowedExceedancePercent <= 100, "ODS:InvalidExceedance", ...
    "Allowed exceedance must be from 0 to 100 percent.");
assert(cfg.reporting.strictAllowedExceedancePercent == 0, ...
    "ODS:StrictExceedance", "The strict operational result requires zero exceedance.");
assert(cfg.reporting.practicalAllowedExceedancePercent >= 0 && ...
    cfg.reporting.practicalAllowedExceedancePercent < 100 && ...
    abs(cfg.reporting.practicalAvailabilityPercent - ...
    (100 - cfg.reporting.practicalAllowedExceedancePercent)) < 1e-10, ...
    "ODS:PracticalAvailability", ...
    "Availability-based reporting must complement the allowed exceedance.");
assert(cfg.site.minimumElevationDeg >= 0 && ...
    cfg.site.minimumElevationDeg < 90, "ODS:InvalidMinimumElevation", ...
    "Minimum elevation must be from zero (geometric horizon) to less than 90 degrees.");
assert(isfinite(cfg.site.antennaFeedHeightAglM) && ...
    cfg.site.antennaFeedHeightAglM > 0, "ODS:InvalidAntennaAglHeight", ...
    "Antenna height above local ground must be positive.");
assert(isfinite(cfg.site.groundOrthometricHeightM) && ...
    isfinite(cfg.site.antennaOrthometricHeightM) && ...
    isfinite(cfg.site.geoidUndulationM) && ...
    isfinite(cfg.site.ellipsoidalHeightM), "ODS:InvalidResolvedHeight", ...
    "DEM, orthometric, geoid, and ellipsoidal heights must be finite.");
assert(abs(cfg.site.antennaOrthometricHeightM - ...
    (cfg.site.groundOrthometricHeightM + ...
    cfg.site.antennaFeedHeightAglM)) < 1e-8, ...
    "ODS:OrthometricHeightChain", ...
    "Antenna orthometric height must equal DEM ground height plus AGL height.");
assert(abs(cfg.site.ellipsoidalHeightM - ...
    (cfg.site.antennaOrthometricHeightM + ...
    cfg.site.geoidUndulationM)) < 1e-8, ...
    "ODS:EllipsoidalHeightChain", ...
    "Ellipsoidal height must equal antenna orthometric height plus geoid undulation.");
assert(all(cfg.search.innerAngleRangeDeg >= 0), "ODS:InvalidInnerAngles", ...
    "Inner angles must be nonnegative.");
assert(all(cfg.search.outerAngleRangeDeg >= 0), "ODS:InvalidOuterAngles", ...
    "Outer angles must be nonnegative.");
assert(cfg.ods.muteMitigationDb >= cfg.ods.steerMitigationDb, ...
    "ODS:InvalidMitigationOrder", ...
    "Mute mitigation must be at least as large as steering mitigation.");
assert(~isfield(cfg.ods, "minimumOperationalOuterAngleDeg") || ...
    (cfg.ods.minimumOperationalOuterAngleDeg >= 0 && ...
    cfg.ods.minimumOperationalOuterAngleDeg <= 180), ...
    "ODS:OperationalOuterFloor", ...
    "Minimum operational outer angle must lie from 0 to 180 degrees.");
assert(~isfield(cfg.antenna, "farAngleGainDbiOverride") || ...
    isfinite(cfg.antenna.farAngleGainDbiOverride), ...
    "ODS:FarAngleReceiveGain", ...
    "Far-angle receive-gain override must be finite when configured.");
assert(cfg.aggregation.maxContributingSatellites >= 1 && ...
    mod(cfg.aggregation.maxContributingSatellites, 1) == 0, ...
    "ODS:InvalidContributingSatelliteCount", ...
    "Maximum contributing satellites must be a positive integer.");
selectionMode = string(cfg.aggregation.selectionMode);
assert(any(selectionMode == ["allEligible", "closestK"]), ...
    "ODS:InvalidAggregationSelectionMode", ...
    "Aggregation selection mode must be 'allEligible' or 'closestK'.");
powerCombinationMode = string(cfg.aggregation.powerCombinationMode);
assert(any(powerCombinationMode == ["linearSum", "dominantOnly"]), ...
    "ODS:InvalidPowerCombinationMode", ...
    "Power-combination mode must be 'linearSum' or 'dominantOnly'.");
if powerCombinationMode == "dominantOnly"
    assert(cfg.aggregation.maxContributingSatellites == 1, ...
        "ODS:DominantContributorLimit", ...
        "Dominant-only mode must specify one effective RFI contributor.");
    assert(string(cfg.aggregation.dominantSelectionStage) == ...
        "preMitigation", "ODS:DominantSelectionStage", ...
        "Corrected model requires pre-mitigation dominant selection.");
end
assert(cfg.beams.numberPerSatellite >= 1 && ...
    mod(cfg.beams.numberPerSatellite, 1) == 0, ...
    "ODS:InvalidBeamCount", "Beam count must be a positive integer.");
assert(cfg.beams.numberPerSatellite == 30, ...
    "ODS:PackedBeamCount", ...
    "The public baseline requires exactly 30 beams per satellite.");
assert(string(cfg.beams.transmitPatternModel) == ...
    "ituRS1528LeoPerBeam", "ODS:TransmitPattern", ...
    "The spot-beam baseline requires the per-beam ITU-R S.1528 LEO pattern.");
assert(abs(cfg.beams.nearSidelobeCrossPointDb + 6.75) < 1e-10, ...
    "ODS:S1528CrossPoint", ...
    "The S.1528 LEO cross-point level must be -6.75 dB.");
assert(cfg.beams.spotHalfPowerRadiusDeg > 0 && ...
    cfg.beams.spotHalfPowerRadiusDeg < cfg.beams.coneHalfAngleDeg, ...
    "ODS:SpotBeamwidth", ...
    "Spot half-power radius must be positive and smaller than the field of regard.");
assert(cfg.beams.offAxisMaskMarginDb >= 0 && ...
    cfg.beams.offAxisMaskTransitionStartNormalized >= 1 && ...
    cfg.beams.offAxisMaskTransitionEndNormalized > ...
    cfg.beams.offAxisMaskTransitionStartNormalized, ...
    "ODS:OffAxisMaskMargin", ...
    "Off-axis mask margin and normalized transition limits are invalid.");
assert(isfinite(cfg.beams.farOutSidelobeGainDbi), ...
    "ODS:S1528FarSidelobe", ...
    "The S.1528 far-out sidelobe gain must be finite.");
assert(string(cfg.beams.scanLossModel) == ...
    "projectedApertureCosine" && ...
    cfg.beams.scanLossCosineExponent > 0 && ...
    cfg.beams.scanLossCompensationEnabled, ...
    "ODS:TransmitScanLoss", ...
    "The baseline requires compensated projected-aperture cosine scan loss.");
assert(string(cfg.beams.layoutModel) == ...
    "optimizedTriangularClosePackedGeodesicCells", ...
    "ODS:PackedLayoutModel", "Unexpected packed-cell layout model.");
assert(isfile(cfg.beams.layoutFile), "ODS:MissingPackedLayout", ...
    "Packed beam-layout file not found: %s", cfg.beams.layoutFile);
layoutTable = readtable(cfg.beams.layoutFile);
requiredLayoutVariables = ["Beam", "PackingX", "PackingY", ...
    "MaximumEdgeOffNadirDeg"];
assert(all(ismember(requiredLayoutVariables, string( ...
    layoutTable.Properties.VariableNames))), "ODS:PackedLayoutVariables", ...
    "Packed beam-layout evidence is missing required variables.");
assert(height(layoutTable) == cfg.beams.numberPerSatellite && ...
    numel(unique(layoutTable.Beam)) == cfg.beams.numberPerSatellite && ...
    all(isfinite(layoutTable.PackingX)) && ...
    all(isfinite(layoutTable.PackingY)), "ODS:PackedLayoutContent", ...
    "Packed beam-layout evidence must contain one finite, unique row per beam.");
assert(max(layoutTable.MaximumEdgeOffNadirDeg) <= ...
    cfg.beams.coneHalfAngleDeg + 1e-8, "ODS:PackedLayoutCone", ...
    "Packed beam-layout evidence extends beyond the configured off-nadir cone.");
assert(cfg.beams.nonOverlapToleranceDeg >= 0, ...
    "ODS:NonOverlapTolerance", ...
    "The packed-cell non-overlap tolerance must be nonnegative.");
assert(cfg.za.enabled && cfg.za.protectedCoreRadiusKm >= 0 && ...
    cfg.za.minimumActiveBeamCenterDistanceKm >= ...
    cfg.za.protectedCoreRadiusKm, "ODS:GeographicZa", ...
    "The active-beam center restriction must equal or exceed the geographic ZA.");
assert(cfg.resources.carrierCount == 4 && ...
    numel(cfg.resources.carrierEdgesHz) == 5 && ...
    all(diff(cfg.resources.carrierEdgesHz) == ...
    cfg.resources.carrierBandwidthHz), "ODS:ResourceCarriers", ...
    "The operational baseline requires four contiguous 5-MHz carriers.");
assert(all(cfg.resources.cochannelBeamIndices >= 1) && ...
    all(cfg.resources.cochannelBeamIndices <= cfg.beams.numberPerSatellite) && ...
    all(cfg.resources.protectedCarrierIndices >= 1) && ...
    all(cfg.resources.protectedCarrierIndices <= cfg.resources.carrierCount) && ...
    all(ismember(cfg.resources.beamCarrierIndex( ...
    cfg.resources.cochannelBeamIndices), ...
    cfg.resources.protectedCarrierIndices)) && ...
    cfg.resources.maximumSimultaneousCochannelBeamsPerSatellite == ...
    numel(cfg.resources.cochannelBeamIndices) && ...
    string(cfg.resources.schedulerMode) == ...
    "independentDemandPerCochannelSpot" && ...
    numel(cfg.resources.beamInterferenceBandwidthHz) == ...
    cfg.beams.numberPerSatellite && ...
    all(cfg.resources.beamInterferenceBandwidthHz( ...
    cfg.resources.cochannelBeamIndices) > 0), ...
    "ODS:ResourceReuse", ...
    "Independent cochannel-spot scheduling or per-beam overlap bandwidth is invalid.");
assert(cfg.resources.meanSatelliteCarrierDutyCycle > 0 && ...
    cfg.resources.meanSatelliteCarrierDutyCycle < 1 && ...
    cfg.resources.meanBeamCarrierDutyCycle == ...
    cfg.resources.meanSatelliteCarrierDutyCycle && ...
    cfg.resources.meanOnDurationSec > 0 && ...
    cfg.resources.meanOffDurationSec > 0, "ODS:TrafficModel", ...
    "Traffic duty cycle and dwell times must be physically valid.");
boundaryMode = string(cfg.beams.transmissionBoundary);
assert(boundaryMode == "nadirConePackedSpots", ...
    "ODS:InvalidTransmissionBoundary", ...
    "Transmission boundary must be 'nadirConePackedSpots'.");
assert(cfg.beams.coneHalfAngleDeg > 0 && ...
    cfg.beams.coneHalfAngleDeg < 90, "ODS:InvalidConeHalfAngle", ...
    "Beam cone half-angle must lie between zero and 90 degrees.");
assert(abs(cfg.beams.fullConeAngleDeg - 2*cfg.beams.coneHalfAngleDeg) < 1e-10, ...
    "ODS:InvalidFullConeAngle", ...
    "Full cone angle must equal twice the cone half-angle.");
assert(isfinite(cfg.rf.eirpDensityDbwPerMHz) && ...
    isfinite(cfg.rf.maximumBeamEirpDensityDbwPerMHz) && ...
    cfg.rf.eirpDensityDbwPerMHz > 0 && ...
    cfg.rf.maximumBeamEirpDensityDbwPerMHz > 0 && ...
    cfg.rf.eirpDensityDbwPerMHz <= ...
    cfg.rf.maximumBeamEirpDensityDbwPerMHz, ...
    "ODS:EirpDensityConfiguration", ...
    "Nominal per-beam EIRP density must be positive and no greater than its configured ceiling.");
assert(abs(cfg.rf.referencePeakAntennaGainDbi - 38) < 1e-10, ...
    "ODS:ReferencePeakGain", ...
    "The S.1528 pattern normalization requires the 38 dBi reference peak gain.");
assert(string(cfg.aggregation.selectionMode) == "allEligible" && ...
    string(cfg.aggregation.powerCombinationMode) == "linearSum", ...
    "ODS:PerBeamAggregateRequired", ...
    "The operational baseline must linearly aggregate all scheduled eligible satellites.");
assert(string(cfg.ods.actionMode) == ...
    "physical outer beam retasking and inner protected-carrier shutdown", ...
    "ODS:PerBeamActionRequired", ...
    "The operational baseline requires physical retasking and exact carrier shutdown.");
assert(cfg.ods.outerMinimumBeamCenterDistanceKm > ...
    cfg.za.minimumActiveBeamCenterDistanceKm && ...
    cfg.ods.innerProtectedCarrierShutdownEnabled, ...
    "ODS:OperationalActions", ...
    "Outer retasking must exceed the ZA radius and inner shutdown must be enabled.");
assert(cfg.calibration.enabled && isfile(cfg.calibration.evidenceFile) && ...
    cfg.calibration.sidelobeCorrectionDb <= 0 && ...
    cfg.calibration.rampStartDistanceKm == 30 && ...
    cfg.calibration.fullCorrectionDistanceKm > ...
    cfg.calibration.rampStartDistanceKm, "ODS:EmpiricalCalibration", ...
    "The NRAO calibration evidence and distance ramp must be valid.");
assert(cfg.propagation.receiverAntennaHeightAglM > 0, ...
    "ODS:InvalidAntennaHeight", "Receiver antenna height must be positive.");
assert(cfg.propagation.clutterRepresentativeHeightM > 0, ...
    "ODS:InvalidClutterHeight", "Representative clutter height must be positive.");
if cfg.propagation.enabled && ...
        string(cfg.propagation.atmosphericModel) == "ituRP618Lookup"
    assert(cfg.propagation.minimumLookupElevationDeg >= ...
        cfg.site.minimumElevationDeg && ...
        cfg.propagation.minimumLookupElevationDeg < 90, ...
        "ODS:InvalidPropagationLookupFloor", ...
        "The P.618 lookup floor must be at or above visibility and below 90 degrees.");
    assert(isfile(cfg.propagation.atmosphericLookupFile), ...
        "ODS:MissingAtmosphericLookup", ...
        "Atmospheric lookup file not found: %s", ...
        cfg.propagation.atmosphericLookupFile);
    atmosphericTable = readtable(cfg.propagation.atmosphericLookupFile);
    requiredAtmosphericVariables = ["ElevationDeg", ...
        "TotalAtmosphericLossDb"];
    assert(all(ismember(requiredAtmosphericVariables,string( ...
        atmosphericTable.Properties.VariableNames))), ...
        "ODS:AtmosphericLookupSchema", ...
        "Atmospheric lookup must contain ElevationDeg and TotalAtmosphericLossDb.");
    elevation = atmosphericTable.ElevationDeg;
    loss = atmosphericTable.TotalAtmosphericLossDb;
    assert(~isempty(elevation) && numel(elevation) == numel(loss) && ...
        all(isfinite(elevation)) && all(isfinite(loss)) && ...
        all(loss >= 0) && all(diff(elevation) > 0) && ...
        elevation(1) <= cfg.propagation.minimumLookupElevationDeg && ...
        elevation(end) >= 90,"ODS:AtmosphericLookupContent", ...
        "Atmospheric lookup data must be finite, nonnegative, strictly " + ...
        "increasing in elevation, and cover the configured floor through 90 degrees.");
end

shells = cfg.constellation.shells;
earthRadiusM = 6378137;
minimumLimbAngleDeg = asind(earthRadiusM/(earthRadiusM + ...
    1000*max([shells.altitudeKm])));
if boundaryMode == "nadirConePackedSpots"
    assert(cfg.beams.coneHalfAngleDeg < minimumLimbAngleDeg, ...
        "ODS:ConeBeyondEarth", ...
        "Beam cone edge must remain inside the Earth limb (%.2f deg).", ...
        minimumLimbAngleDeg);
end
for idx = 1:numel(shells)
    assert(mod(shells(idx).satellites, shells(idx).planes) == 0, ...
        "ODS:InvalidWalkerShell", ...
        "Satellites must divide evenly among planes in shell %s.", shells(idx).name);
end
end

function secondsValue = durationValueSeconds(value)
if isduration(value)
    secondsValue = seconds(value);
else
    secondsValue = double(value);
end
end
